### ISSUE TITLE
Blank nodes in `CONSTRUCT` output

### ISSUE THREAD

**Issue by namedgraph** [comunica/comunica#1190] opened 2023-04-03 10:36 UTC
I don't think Comunica is interpreting the spec correctly here re. blank nodes.

#### Issue type:

- :bug: Bug 

____
#### Description:

I would expect a single bnode in the result, instead I'm getting multiple.

Input:
```turtle
BASE   <http://example.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>

_:bob
    a foaf:Person ;
    foaf:knows <alice#me> ;
    schema:birthDate "1990-07-04"^^xsd:date ;
    foaf:topic_interest wd:Q12418 .
```
Query:
```sparql
CONSTRUCT WHERE
{
    ?s ?p ?o
}
```
Comunica output:
```turtle
_:bc_0_b2_bob0 a <http://xmlns.com/foaf/0.1/Person>.
_:bc_0_b2_bob1 <http://xmlns.com/foaf/0.1/knows> <http://example.org/alice#me>.
_:bc_0_b2_bob2 <http://schema.org/birthDate> "1990-07-04"^^<http://www.w3.org/2001/XMLSchema#date>.
_:bc_0_b2_bob3 <http://xmlns.com/foaf/0.1/topic_interest> <http://www.wikidata.org/entity/Q12418>.
```
Jena output:
```turtle
@prefix schema: <http://schema.org/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix wd:    <http://www.wikidata.org/entity/> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .

[ a                    foaf:Person ;
  schema:birthDate     "1990-07-04"^^xsd:date ;
  foaf:knows           <http://example.org/alice#me> ;
  foaf:topic_interest  wd:Q12418
] .
```
____
#### Environment:

```html
<script src="https://rdf.js.org/comunica-browser/versions/v2/engines/query-sparql/comunica-browser.js"></script>
```

**Comment by jeswr** [comment] 2023-04-03 10:41
This is a dupe of https://github.com/comunica/comunica/issues/1160

**Comment by rubensworks** [comment] 2023-04-03 10:46
The query is equivalent to the following:
```sparql
CONSTRUCT
{
    ?s ?p ?o
}
WHERE
{
    ?s ?p ?o
}
```

The `WHERE` clause will be executed first, and will produce one query solution for each triple inside the dataset.
For each query solution, the query template will be instantiated.
According to what the SPARQL spec says, blank nodes will be scoped per query solution:

> The blank node labels are scoped to the template for each solution.

So based on my understanding of the spec, this behaviour is correct.

The example in https://www.w3.org/TR/sparql11-query/#templatesWithBNodes aligns with this.

**Comment by namedgraph** [comment] 2023-04-03 10:49
I'm sorry but I'll trust Jena on this.

Note that there are no bnodes _in my query_ (which is what that section is about), only _in my data_.

**Comment by afs** [comment] 2023-04-03 11:18
Blank nodes in the template are unique across the solution mappings used while instantiating the template.

The query `CONSTRUCT WHERE { ?S ?P ?O }` has a template of `{ ?S ?P ?O }` which has no blank nodes.

Blank nodes from the WHERE clause are not affected - they are just data.

**Comment by rubensworks** [comment] 2023-04-03 11:20
Ok, then our implementation in Comunica is incorrect.
(and I'm actually happy about this, as it will allow us to significantly simplify things)

Thanks for the input @afs!

**Comment by afs** [comment] 2023-04-03 11:26
And anyone can make a PR to [w3c/sparql-query](https://github.com/w3c/sparql-query) improve the spec text 😄

**Closed** 2023-05-04 06:56 UTC
Labels: bug 🐛, difficulty:low, effort:medium
