### ISSUE TITLE
Send original SPARQL query string to endpoints

### ISSUE THREAD

**Issue by sdevalk** [comunica/comunica#844] opened 2021-07-28 15:44 UTC
_This issue has been modified by @rubensworks to describe the intended solution_

The problem is that we always parse the incoming query, and serialize it again when we send it to a SPARQL endpoint. Since this parsing-serializing process sometimes results in slightly different queries, this may cause issues for certain use cases. To solve this, we need to keep track of the original query string, and use that one in the case of querying a SPARQL endpoint.

In actor-init-sparql, we need to add the original query string into the context.
In `actor-query-operation-sparql-endpoint`, we need to check this context entry, and use that one if it exists.

The only difficulty here is that we have to make sure that this context entry does not propagate to places where it shouldn't. For example, if this actor is only used because of a `SERVICE` keyword, we need to make sure that the actor still uses the `SERVICE` operation instead of the full original query. We could do this by just making sure that the service operator unsets or overrides this entry.

-----

Original issue:

#### Issue type:

- :question: Question 

____
#### Question:

I want to query SPARQL endpoint `https://data.muziekschatten.nl/sparql`, backed by Virtuoso, using the query underneath:

```sparql
SELECT * WHERE {
  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person>;
    <http://schema.org/name> ?label.
  FILTER(<bif:contains>(?label, "emile"))
  BIND("no name" AS ?name)
}
LIMIT 100
```

It's a silly query - but the crucial parts are the `FILTER` and the `BIND`. If I execute this using Comunica...

`npx comunica-sparql sparql@https://data.muziekschatten.nl/sparql -f query.rq`

...where file `query.rq` contains the query above...then the result is:

`[Invalid SPARQL endpoint (https://data.muziekschatten.nl/sparql) response: undefined`

My guess is that Comunica is rewriting the query, e.g. to:

```sparql
SELECT * WHERE {
  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person>;
    <http://schema.org/name> ?label.
  BIND("no name" AS ?name)
  FILTER(<bif:contains>(?label, "emile"))
}
LIMIT 100
```

`FILTER` is placed after `BIND`. If I execute this query via the endpoint's query editor on `https://data.muziekschatten.nl/sparql`, then Virtuoso yields the error:

`Virtuoso 37000 Error SP031: SPARQL compiler: The group does not contain triple pattern with '$label' object before bif:contains() predicate`.

Is it possible to influence the way that Comunica rewrites the query?

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Netwerk Digitaal Erfgoed" src="https://user-images.githubusercontent.com/440384/134636829-f730230c-bfec-4d40-86d1-67f28479cdcc.png" height="25">](https://netwerkdigitaalerfgoed.nl/) |
| €544 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment] 2021-07-29 06:07
Indeed, you're right. For some reason, the two operators are swapped.
This is the response from the endpoint:
```
Virtuoso 37000 Error SP031: SPARQL compiler: The group does not contain triple pattern with '$label' object before bif:contains() predicate

SPARQL query:
define sql:big-data-const 0 SELECT ?uri ?label ?name WHERE {
  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person>;
    <http://schema.org/name> ?label.
  BIND("no name" AS ?name)
  FILTER(<bif:contains>(?label, "emile"))
}
LIMIT 100
```

@joachimvh I suspect this is due to roundtripping to/from sparql algebra.
Do you think this is something that is easily fixable?

Worst case, we need to figure out a mechanism that does not parse the input query to algebra at all, but sends the original query as-is to the endpoint.

**Comment by joachimvh** [comment] 2021-07-29 06:42
This is quite certainly the algebra. The SPARQL spec says that FILTER operations apply to the entire group graph pattern, independent of their position so those get handled separately: https://www.w3.org/TR/sparql11-query/#sparqlCollectFilters . So when converting back to SPARQL those would always be added at the end.

I don't really see why Virtuoso would throw an error on that query though, the FILTER is still preceded by a pattern that contains the specified variable. Unless Virtuoso requires the triple to be immediately preceding (which would be a wrong interpretation of the SPARQL spec imo)?

In case this is needed the only solution would indeed be to bypass the algebra conversion.

I also had a look at the docs of `bif:contains`. It is apparently also possible to write it as a triple http://docs.openlinksw.com/virtuoso/rdfsparqlrulefulltext/ . So this query can also be written as
```sparql
SELECT ?uri ?label ?name WHERE {
  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person>;
    <http://schema.org/name> ?label.
  ?label bif:contains "'emile'".
  BIND("no name" AS ?name)
}
LIMIT 100
```
which might work. Not saying that Comunica should do this, but this might be a solution now for people running into this problem.

**Comment by rubensworks** [comment] 2021-07-29 06:45
> In case this is needed the only solution would indeed be to bypass the algebra conversion.

Yeah, that might be a good long-term solution.
Because I've seen similar issues to this one when queries (that go outside of the sparql spec) are forwarded to specific sparql endpoint.

> I also had a look at the docs of bif:contains. It is apparently also possible to write it as a triple http://docs.openlinksw.com/virtuoso/rdfsparqlrulefulltext/ . So this query can also be written as

Nice find, this might help @sdevalk in the meantime.

**Comment by sdevalk** [comment] 2021-07-30 08:02
@joachimvh & @rubensworks Thank you! I'll certainly give `?label bif:contains "'emile'"` a try!

**Comment by ddeboer** [comment] 2021-10-30 11:26
As far as I can see, `?label bif:contains "search string"` will not work with a variable, which is what we need:

```sparql
BIND("'emile'" as ?query)
?label <bif:contains> ?query
```

gives:

```
Virtuoso 22023 Error SR468: contains() can not be called as plain built-in function, it's a macro handled by SQL compiler
```

**Comment by jasmineleonard** [comment] 2021-11-24 14:23
As discussed with @rubensworks, I will work on this issue via the Comunica Association.

**Comment by ddeboer** [comment] 2021-11-24 16:46
That’s great news! 

@jasmineleonard Please let us know in case  you need more info to debug the issue.

**Comment by rubensworks** [comment] 2021-11-26 14:51
@jasmineleonard Thanks again for the PR!
Just to double-check, could you confirm that the query execution on the endpoint mentioned in the first post of this issue now works as intended?
If so, we can close this issue, and finalize the bounty.

**Comment by jasmineleonard** [comment] 2021-11-26 15:23
Thanks @rubensworks ! 

I can confirm that the query execution on the endpoint mentioned in the first post of this issue now works as intended. 

That is, querying`https://data.muziekschatten.nl/sparql` with

```sql
SELECT * WHERE {
  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person>;
    <http://schema.org/name> ?label.
  FILTER(<bif:contains>(?label, "emile"))
  BIND("no name" AS ?name)
}
LIMIT 100
```

now returns a valid list of results.

**Comment by rubensworks** [comment] 2021-11-26 15:26
Super, great work! Let's discuss next steps during our call next week.

**Closed by rubensworks** 2021-11-26 15:26 UTC
Labels: question ❓, difficulty:low, effort:low, comunica-association-bounty
