### ISSUE TITLE
Simple two-triple-pattern query on Linked Data document is slow

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#420] opened 2019-03-11 08:52 UTC
#### Issue type:

- :snail: Performance issue

____
#### Description:

This query is unexpectedly slow:
http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdrive.verborgh.org%2Fpublic%2Factivities&query=SELECT%20%3Factivity%20WHERE%20%7B%0A%20%20%3Factivity%20%3Chttps%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%23actor%3E%20%3Chttps%3A%2F%2Fruben.verborgh.org%2Fprofile%2F%23me%3E%3B%0A%20%20%20%20%20%20%3Chttps%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%23object%3E%20%3Fobject.%0A%7D%0A

____

**Comment by rubensworks** [comment] 2019-03-11 08:54
Probably because of the adaptive BGP algorithm. An alternative joining algorithm would be better here. We may want to look into different joining algorithms based on the source types.

**Comment by rubensworks** [comment] 2019-06-25 13:07
For reference, when executing this query from the command-line, it _only_ takes 1,5 seconds, instead of 4,6 seconds in the browser. So it _may_ just have something to do with the jQuery widget.

**Comment by RubenVerborgh** [comment] 2019-06-25 13:16
That's weird; all query work happens in a worker, right?

**Comment by rubensworks** [comment] 2019-06-25 13:18
Yep, everything should be running in a worker: https://github.com/comunica/jQuery-Widget.js/blob/master/src/ldf-client-worker.js

It's pretty much the same code as for the LDF client.

Something else might be going wrong, will have to look into that.

**Comment by pietercolpaert** [comment] 2019-09-25 10:58
At the moment the interface gives me 317 results in 1.2s. Is this issue fixed?

**Comment by rubensworks** [comment] 2019-09-25 11:04
@pietercolpaert I assume you are talking about the CLI?
We can definitely improve the performance of that, but that will require us to get into implementing different join algorithms, and their usage heuristics.
Definitely something we should do at some point, but it will require quite a bit of effort.

**Comment by pietercolpaert** [comment] 2019-09-25 11:06
I tested the link given by Ruben at the top. The results seem fast

**Comment by rubensworks** [comment] 2019-09-25 11:10
Ah yes, results are definitely faster than before, but not fast enough, which is why I haven't closed this issue yet.

Two main problems remain:
* Web client emits results slower than CLI.
* Overall speed can be improved by using different joining algorithms in file sources.

**Comment by rubensworks** [comment] 2020-03-27 13:03
Root cause seems to be #561

**Closed by rubensworks** 2020-03-27 13:03 UTC
Labels: performance 🐌
