### ISSUE TITLE
Yarn run prepare not working on Windows

### ISSUE THREAD

**Issue by FlorianFV** [comunica/comunica#713] opened 2020-08-17 11:27 UTC
#### Issue type:

- :bug: Bug

____
#### Description:

I wanted to change the http.json file in actor-init-sparql to use the ActorHttpNodeFetch instead of the ActorHttpNative.
The output doesn't change in engine-default.js when I changed the correct fields. Even a JSON syntax error did not let the `yarn run prepare` fail (in http.json).
When I typed a syntax error in config-default.json, it did crash.

____
#### Environment:

Windows.

**Comment by rubensworks** [comment] 2020-08-17 13:49
Looks like a windows-specific problem in Components.js.
Something probably goes wrong when handling `import`: https://github.com/LinkedSoftwareDependencies/Components.js/blob/master/lib/rdf/RdfStreamIncluder.ts#L35

@joachimvh Could you have a look at this one? (not very urgent)

**Comment by joachimvh** [comment] 2020-09-16 08:51
I just had a look at this and I can't reproduce. I changed the type in `actor-init-sparql/config/sets/http.json` to `ActorHttpNodeFetch` and the corresponding context value, and it appeared in the `config-default.json`. Not sure if something changed to Components.js in the meantime that might have fixed this.

**Comment by rubensworks** [comment] 2020-09-16 09:01
Might be related to #616. If so, then it may not apply to all Node versions: https://github.com/comunica/comunica/issues/616#issuecomment-597564220

**Comment by rubensworks** [comment] 2022-03-03 13:54
Considering this resolved in Comunica 2

**Closed by rubensworks** 2022-03-03 13:54 UTC
Labels: bug 🐛, core, difficulty:low, effort:low
