### ISSUE TITLE
Querying the actor-init-sparql http endpoint does not work anymore with RDF4J

### ISSUE THREAD

**Issue by vemonet** [comunica/comunica#766] opened 2020-12-08 14:40 UTC
#### Issue type:

- :bug: Bug 

____
#### Description:

`SELECT` query on a HTTP SPARQL endpoint deployed using the `actor-init-sparql` Docker image does not work with RDF4J

In issue https://github.com/comunica/comunica/issues/762 it is said the default response has been fixed for version `1.18.1` and I can see it when I do a quick query to the SPARQL endpoint: [click here to see default SPARQL results](http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+bl%3A+%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0APREFIX+d2s%3A+%3Chttps%3A%2F%2Fw3id.org%2Fd2s%2F%3E%0APREFIX+sio%3A+%3Chttp%3A%2F%2Fsemanticscience.org%2Fresource%2F%3E%0APREFIX+bio2rdf%3A+%3Chttp%3A%2F%2Fbio2rdf.org%2F%3E%0APREFIX+covid%3A+%3Chttp%3A%2F%2Fidlab.github.io%2Fcovid19%23%3E%0APREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX+dctypes%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fdcmitype%2F%3E%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX+idot%3A+%3Chttp%3A%2F%2Fidentifiers.org%2Fidot%2F%3E%0APREFIX+dcat%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX+void%3A+%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0APREFIX+void-ext%3A+%3Chttp%3A%2F%2Fldf.fi%2Fvoid-ext%23%3E%0APREFIX+obo%3A+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%3E%0APREFIX+ncit%3A+%3Chttp%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX+omop%3A+%3Chttp%3A%2F%2Fapi.ohdsi.org%2FWebAPI%2Fvocabulary%2Fconcept%2F%3E%0APREFIX+cohd%3A+%3Chttps%3A%2F%2Fw3id.org%2Ftrek%2Fcohd%2F%3E%0ASELECT+DISTINCT+%3Fn00+%3Fn00name+%3Fn01+%3Fn01name+%3Fe00+WHERE+{+%0A%3Fn00+a+bl%3ADrug.+%0AOPTIONAL+{%3Fn00+bl%3Aname+%3Fn00name+.+}%0A%3Fn01+a+bl%3ADisease.+%0AOPTIONAL+{%3Fn01+bl%3Aname+%3Fn01name+.+}%0A%3Fe00+a+bl%3AAssociation.+%0A%3Fe00+bl%3Asubject+%3Fn00+.+%0A%3Fe00+bl%3Aobject+%3Fn01+.+%0A})

But querying using RDF4J is not working anymore (the exact same piece of code worked a few weeks ago, and is a quite straightforward way to query a SPARQL endpoint using RDF4J and SELECT queries):

```java
public TupleQueryResult executeSparqlSelect(String queryString) {
		logger.fine(queryString.trim().replaceAll("\\s+", " "));
		SPARQLRepository repo = getRepo();
		TupleQueryResult selectResults = null;
		try {
			RepositoryConnection conn = repo.getConnection();
			TupleQuery tupleQuery = conn.prepareTupleQuery(queryString);
			selectResults = tupleQuery.evaluate();
		} finally {
			repo.getConnection().close();
		}
		return selectResults;
	}
```

Running this RDF4J iece of code on the Comunica HTTP SPARQL endpoint gives the error `Expected SPARQL Results JSON document to start with an Object`

```
org.eclipse.rdf4j.query.resultio.QueryResultParseException: Expected SPARQL Results JSON document to start with an Object
	at org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONParser.parseQueryResultInternal(AbstractSPARQLJSONParser.java:121) ~[rdf4j-queryresultio-sparqljson-3.0.4.jar!/:3.0.4+47737c0]
	at org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONParser.parseQueryResult(AbstractSPARQLJSONParser.java:103) ~[rdf4j-queryresultio-sparqljson-3.0.4.jar!/:3.0.4+47737c0]
	at org.eclipse.rdf4j.query.resultio.helpers.BackgroundTupleResult.run(BackgroundTupleResult.java:89) ~[rdf4j-queryresultio-api-3.0.4.jar!/:3.0.4+47737c0]
	at org.eclipse.rdf4j.http.client.BackgroundResultExecutor.lambda$autoCloseRunnable$0(BackgroundResultExecutor.java:65) ~[rdf4j-http-client-3.0.4.jar!/:3.0.4+47737c0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_275]
```

I also tried adding the accept header in rdf4j, but still getting the same error:

```java
headers.put("Accept", "application/sparql-results+json");
repo.setAdditionalHttpHeaders(headers);
```

The `actor-init-sparql` Docker logs show that the SPARQL endpoint gets the query from RDF4J without issue, with the right requested media:

![Screenshot from 2020-12-08 15-26-27](https://user-images.githubusercontent.com/3778439/101496784-7a884680-396a-11eb-878f-dfc104a1aa13.png)

But when RDF4J get the results back it is complaining about the format: `Expected SPARQL Results JSON document to start with an Object` (cf. above for the complete error message)

____
#### Environment:

* RDF4J

RDF4J running on Ubuntu 18.04 with Java: 
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

* SPARQL endpoint

`actor-init-sparql` HTTP endpoint running publicly on a Centos 7 server at http://nanopub-sparql.137.120.31.102.nip.io/sparql

docker version:
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
```

We use this [docker-compose.yml](https://github.com/MaastrichtU-IDS/knowledge-collaboratory-api/blob/master/docker-compose.yml)

```yaml
  comunica-sparql-endpoint:
    container_name: nanopub-sparql
    # image: comunica/actor-init-sparql:latest
    image: comunica/actor-init-sparql:1.18.1
    restart: unless-stopped
    entrypoint: node ./bin/http.js http://ldf.np.dumontierlab.com/np
    ports:
      - 3000:3000
    environment: 
      # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
      VIRTUAL_HOST: nanopub-sparql.137.120.31.102.nip.io
      VIRTUAL_PORT: 3000
```

#### Crash log:

Do you have any idea why RDF4J is not able to perform a SELECT query against the Comunica HTTP SPARQL endpoint?

**Comment by rubensworks** [comment] 2020-12-09 11:04
@vemonet If I execute [your query](http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+bl%3A+%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0APREFIX+d2s%3A+%3Chttps%3A%2F%2Fw3id.org%2Fd2s%2F%3E%0APREFIX+sio%3A+%3Chttp%3A%2F%2Fsemanticscience.org%2Fresource%2F%3E%0APREFIX+bio2rdf%3A+%3Chttp%3A%2F%2Fbio2rdf.org%2F%3E%0APREFIX+covid%3A+%3Chttp%3A%2F%2Fidlab.github.io%2Fcovid19%23%3E%0APREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX+dctypes%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fdcmitype%2F%3E%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX+idot%3A+%3Chttp%3A%2F%2Fidentifiers.org%2Fidot%2F%3E%0APREFIX+dcat%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX+void%3A+%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0APREFIX+void-ext%3A+%3Chttp%3A%2F%2Fldf.fi%2Fvoid-ext%23%3E%0APREFIX+obo%3A+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%3E%0APREFIX+ncit%3A+%3Chttp%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX+omop%3A+%3Chttp%3A%2F%2Fapi.ohdsi.org%2FWebAPI%2Fvocabulary%2Fconcept%2F%3E%0APREFIX+cohd%3A+%3Chttps%3A%2F%2Fw3id.org%2Ftrek%2Fcohd%2F%3E%0ASELECT+DISTINCT+%3Fn00+%3Fn00name+%3Fn01+%3Fn01name+%3Fe00+WHERE+%7B+%0A%3Fn00+a+bl%3ADrug.+%0AOPTIONAL+%7B%3Fn00+bl%3Aname+%3Fn00name+.+%7D%0A%3Fn01+a+bl%3ADisease.+%0AOPTIONAL+%7B%3Fn01+bl%3Aname+%3Fn01name+.+%7D%0A%3Fe00+a+bl%3AAssociation.+%0A%3Fe00+bl%3Asubject+%3Fn00+.+%0A%3Fe00+bl%3Aobject+%3Fn01+.+%0A%7D), the SPARQL/JSON result seems to be incomplete, and the response seems to be infinitely loading.

It is possible that the query is failing somehow, and an error message is being emitted on the console?
That could explain the RDF4J parser failing on it.

Side-note, also Comunica itself is unable to query your instance: http://query.linkeddatafragments.org/#datasources=http%3A%2F%2Fnanopub-sparql.137.120.31.102.nip.io%2Fsparql&query=CONSTRUCT%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%20100
(Even though this should work)

So I suspect your underlying datasource is having issues? (What one are you using?)

**Comment by vemonet** [comment] 2020-12-09 16:37
Interesting, note that I managed to `SELECT` query http://nanopub-sparql.137.120.31.102.nip.io/sparql using SPARQLWrapper in Python, my firefox browser and Bash! So the LDF server should be able to do it, especially that those are part of the same stack

I am trying to query a Linked Data Fragment server from the Nanopublication network: https://github.com/peta-pico/nanopub-services/blob/master/docker-compose.yml#L68

But the combination of a Linked Data Fragment server and Comunica engine seems to be really unstable, I managed to get some data out last time with even more complexe queries, and now it freezes for the simplest query when I come back

So I just restarted the Comunica `actor-init-sparql` container, and it now works:

http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=SELECT%20*%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%201

Mandatory screenshot before it crashes:

![Screenshot from 2020-12-09 17-28-33](https://user-images.githubusercontent.com/3778439/101657447-30739380-3a44-11eb-872d-b603e2389958.png)


Note that most of the time where I leave this SPARQL endpoint running for a few days and I come back to it it gives me unconsistent and erroneous results, requiring a restart to make it work

http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=SELECT%20*%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%201

The previous `docker-compose logs` (of the failing Comunica SPARQL endpoint) contained those error, but not sure if it is really relevant to the issue

```
[500] Server error in results: write EPIPE 
```

You can find the docker-compose.yaml to start the `actor-init-sparql` here:
https://github.com/MaastrichtU-IDS/knowledge-collaboratory-api/blob/master/docker-compose.yml#L22

You can find the Nanopub LDF docker-compose here: https://github.com/peta-pico/nanopub-services/blob/master/docker-compose.yml#L69

The best way to query programmatically a SPARQL endpoint is still, and might stay forever: the mighty `wget` and the legendary `curl` (as long as you encode the query you pass):

```
curl -X GET "http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=SELECT%20*%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%201"
```

It works flawlessly and is dead simple to use. Java and Python RDF libs should just wrap this call honestly instead of losing their time reimplementing it in less efficient languages

**Comment by vemonet** [comment] 2020-12-09 17:00
Querying using the LDF web UI returns this in the logs:

```
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix skos: <http://www.w3.org/2004/02/skos/core#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dc: <http://purl.org/dc/terms/>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix dbpedia: <http://dbpedia.org/resource/>.
@prefix dbpedia-owl: <http://dbpedia.org/ontology/>.
@prefix dbpprop: <http://dbpedia.org/property/>.
@prefix wdprop: <http://www.wikidata.org/prop/direct/>.
@prefix ruben: <https://ruben.verborgh.org/profile/#>.
@prefix rubent: <https://www.rubensworks.net/#>.
@prefix schema: <http://schema.org/>.
@prefix bow: <https://betweenourworlds.org/ontology/>.
@prefix lc: <http://semweb.mmlab.be/ns/linkedconnections#>.

# Error: Invalid JSON (Unexpected "A" at position 26762605 in state STOP)
```

And they do this query:

Requesting http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D {"headers":{"accept":"application/sparql-results+json","user-agent":"Comunica/actor-http-native (Browser-Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0)"},"actor":"https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher"}

Which seems to be generating a wrong JSON file:
![Screenshot from 2020-12-09 17-56-13](https://user-images.githubusercontent.com/3778439/101661033-16d44b00-3a48-11eb-806e-a39461e1b7c3.png)

See raw data:

![Screenshot from 2020-12-09 17-56-18](https://user-images.githubusercontent.com/3778439/101661030-163bb480-3a48-11eb-8257-f8cec6af0736.png)


Conclusion: 
* The Comunica HTTP SPARQL endpoint seems to return a correct JSON when queried via Browser, Python SPARQLWrapper and Bash
* The Comunica HTTP SPARQL endpoint response format seems to have some things that cause RDF4J and Comunica to properly parse the `SELECT` and `CONSTRUCT` responses

**Comment by vemonet** [comment] 2020-12-09 18:00
Now changing the query from `CONSTRUCT` to `SELECT` to remove potential issue related to building the RDF

```sparql
SELECT * WHERE {
  ?s ?p ?o.
}
LIMIT 1
```

![Screenshot from 2020-12-09 18-58-08](https://user-images.githubusercontent.com/3778439/101668189-83ebde80-3a50-11eb-8b34-1d0484d49ea7.png)

Clicking on the 2nd "Requesting" link:

Requesting http://nanopub-sparql.137.120.31.102.nip.io/sparql?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D {"headers":{"accept":"application/sparql-results+json","user-agent":"Comunica/actor-http-native (Browser-Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0)"},"actor":"https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher"}

The `LIMIT 1` is removed by Comunica, which obviously makes the query fails.

![Screenshot from 2020-12-09 18-59-54](https://user-images.githubusercontent.com/3778439/101668374-c0b7d580-3a50-11eb-84b3-36d747a3b594.png)

**Comment by rubensworks** [comment] 2020-12-10 07:31
Just to make sure I understand your setup, does it look like this?

> LDF server -> Comunica SPARQL endpoint -> RDF4J

If so, what source type are you using for the LDF server (and what server version are you using)?

> [500] Server error in results: write EPIPE 

This _may_ be related to the problem, but shouldn't.

So it sounds like the Comunica SPARQL endpoint for some reason is getting corrupted. Either due to an HTTP state or query cache bug.

For debugging purposes, it would be good if you could share a minimally reproducible setup in which the problem always occurs.

**Comment by vemonet** [comment] 2020-12-10 11:59
I provided all the pointers to the docker-compose files used in practice above:

1. You can find the `docker-compose.yml` to start the actor-init-sparql here:
https://github.com/MaastrichtU-IDS/knowledge-collaboratory-api/blob/master/docker-compose.yml#L22

2. You can find the Nanopub LDF server here: http://ldf.np.dumontierlab.com/np

Unfortunately the LDF web UI does not show the version of the server

![Screenshot from 2020-12-10 12-52-11](https://user-images.githubusercontent.com/3778439/101769003-9e709700-3ae6-11eb-85af-359f1314dc43.png)

But you can find the `docker-compose.yml` to deploy the LDF server here: https://github.com/peta-pico/nanopub-services/blob/master/docker-compose.yml#L69

```yaml
  ldf:
    image: nanopub/ldf
    ports:
      - 7882:3000
```

Which uses this image: https://hub.docker.com/r/nanopub/ldf

Which is built from this GitHub repository: https://github.com/peta-pico/nanopub-ldf-server-js/tree/master (a fork of https://github.com/LinkedDataFragments/Server.js )

Which seems to have been forked around version 2.2.2 of the npm package

**Comment by rubensworks** [comment] 2023-07-10 07:03
It looks like the links provided in this issue are not available anymore, which makes it difficult to debug this problem.
Furthermore, many changes were made related to SPARQL endpoint querying, so this issue may very well be resolved already.

Closing this issue due to staleness.
Happy to re-open in case this would still be an issue.

**Closed by rubensworks** 2023-07-10 07:03 UTC
Labels: bug 🐛, difficulty:low, effort:high
