### ISSUE TITLE
Default config doesn't open in JSON-LD playground

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#149] opened 2018-06-09 14:39 UTC
#### Issue type:

- :bug: Bug

____
#### Description:

Not sure if this is our problem, but copy/pasting the contents of https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/config/config-default.json into https://json-ld.org/playground/ results in

```
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```

**Comment by rubensworks** [comment] 2018-06-10 06:39
Ah, yes, the contexts don't dereference at the moment.

Components.js has a built-in feature that allows local dereferencing of these files. But that won't work for JSON-LD in general.

Ideally, we should make the LSD server dereference contexts like this: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-abstract-mediatyped/context.jsonld
This should be possible, as these contexts are published to NPM and are linked via the `package.json` file.

@joachimvh What do you think?

**Comment by joachimvh** [comment] 2018-06-11 07:34
Shouldn't we put the contexts at their URI (e.g. https://linkedsoftwaredependencies.org/contexts/comunica-actor-abstract-mediatyped.jsonld )? Or do you mean redirect to the npm server then?

Since the npm server only parses the package.json, it currently looks like this at https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-abstract-mediatyped/1.0.0 :
```json
"lsd:contexts": {
  "https://linkedsoftwaredependencies.org/contexts/comunica-actor-abstract-mediatyped.jsonld": "components/context.jsonld"
},
```
This tells the npm server where the context is located in the tarball, but the problem is that the npm server would then have to actually download the tarball and extract it to find that file (which increases the work of the npm server and might cause it to do many calls to the actual npm registry, depending on how often these calls occur).

Also currently the context is tied to the version of the npm package (i.e., different versions could have different contexts files). Would that link that you suggest than always link to the one of the latest version?

**Comment by RubenVerborgh** [comment] 2018-06-11 07:36
> Also currently the context is tied to the version of the npm package (i.e., different versions could have different contexts files).

If so, they should have different URIs.

**Comment by rubensworks** [comment] 2018-06-11 09:17
> Shouldn't we put the contexts at their URI 

Yes, the URIs need to be changed. The current ones are placeholders that we forgot we had.

> but the problem is that the npm server would then have to actually download the tarball and extract it to find that file

It would be cool if we could do that. Would it actually be such a performance issue? Caching could help out a lot here. And we don't have to unpack the whole tarball.

> Also currently the context is tied to the version of the npm package

Hmm, I haven't thought of this. But indeed, we should probably version our contexts then. We could additionally make a `latest` version, so that our context link in the `package.json` (and config file) does not need updating on every version bump, and simply let the server redirect this `latest` to the appropriate version. But this definitely needs some more thought.

**Comment by RubenVerborgh** [comment] 2018-06-11 09:21
> It would be cool if we could do that. Would it actually be such a performance issue? Caching could help out a lot here. And we don't have to unpack the whole tarball.

Definitely caching. Tarball only if needed.

> But indeed, we should probably version our contexts then. 

I think we should go with semver, i.e., the context should be backwards compatible for all minor version changes (only additions), and a new context version can be minted for breaking changes (major version changes). So only major version numbers in context URIs.

**Comment by joachimvh** [comment] 2018-06-12 09:59
>I think we should go with semver, i.e., the context should be backwards compatible for all minor version changes (only additions), and a new context version can be minted for breaking changes (major version changes). So only major version numbers in context URIs.

The context version number is tied to the version number of the package it is in, so its version number could still increase even if nothing changed to it (since something might have changed to the accompanying package). Practically this is not really a problem I think but might cause there to be a lot of "versions" to be out there of a context.

**Comment by RubenVerborgh** [comment] 2018-06-12 10:08
> The context version number is tied to the version number of the package it is in,

Yes, but my argument is that dereferenceable IRIs of the context should only be tied to the _major_ version number.

> Practically this is not really a problem I think but might cause there to be a lot of "versions" to be out there of a context.

…and I would want to avoid that, as this does not help interoperability.

**Comment by rubensworks** [comment] 2018-06-12 10:14
So in summary, we should be able to expose things like this: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-abstract-mediatyped/^1.0.0/context.jsonld

**Comment by RubenVerborgh** [comment] 2018-06-12 10:15
Wonderful!

…with conneg on https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-abstract-mediatyped/components/context.jsonld of course ;-)

**Comment by RubenVerborgh** [comment] 2018-06-12 10:15
(and bonus points for not having .jsonld :p)

**Comment by joachimvh** [comment] 2018-06-12 11:34
> So in summary, we should be able to expose things like this: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-abstract-mediatyped/^1.0.0/components/context.jsonld

I'm assuming `components/context.jsonld` comes from having the following in the package.json
```json
"lsd:contexts": {
"https://linkedsoftwaredependencies.org/contexts/comunica-actor-abstract-mediatyped.jsonld": "components/context.jsonld"
},
```

So would the idea then be that everytime something is added to the URL we check the tarball for that path? Or only if there is a corresponding lsd:contexts entry? This does sort of tie the URL to where the file is located in the the tarball (but this is probably not going to change).

**Comment by rubensworks** [comment] 2018-06-12 11:38
> So would the idea then be that everytime something is added to the URL we check the tarball for that path?

I think this would be the simplest thing to do, yes. But maybe to avoid the LSD server becoming used as a CDN for any npm package, we could have a file white/blacklist.

**Comment by rubensworks** [comment] 2018-06-18 09:11
Nice!

> What should lsd:contexts be translated to?

Yeah, we'll need a new predicate for this. Not sure if `oo` is the appropriate place for this. Should we add this to the `npm` vocab? Or perhaps even create a new one? (It's possible though that there is some obscure vocab out there that allows you to link to JSON-LD contexts)

**Comment by rubensworks** [comment] 2018-07-04 08:10
FYI, I'm updating the context URLs as part of #25.

**Comment by rubensworks** [comment] 2018-07-26 06:29
This will be fixed once we publish a new release on npm (and our LSD proxy catches up with it)

**Closed by rubensworks** 2018-07-26 06:29 UTC
Labels: bug, enhancement, task
