### ISSUE TITLE
SPARQL endpoint CONSTRUCT queries crash

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#629] opened 2020-03-18 16:20 UTC
#### Issue type:

- :bug: Bug

____
#### Description:

Executing a CONSTRUCT query against a SPARQL endpoint seems to cause an error in the SPARQL algebra.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0
| node                | v10.15.3
| npm                 | 6.11.3
| yarn                | 1.10.1
| Operating System    | darwin (Darwin 17.7.0)

#### Crash log:

```
rtaelman@zimmer ~ 🔷  comunica-sparql sparql@https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100"
TypeError: Cannot read property '0' of undefined
    at translateSlice (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:415:30)
    at translateOperation (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:55:34)
    at translateConstruct (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:170:13)
    at translateOperation (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:38:38)
    at translateProject (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:326:26)
    at translateOperation (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:52:36)
    at toSparqlJs (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:18:18)
    at Object.toSparql (/Users/rtaelman/.config/yarn/global/node_modules/sparqlalgebrajs/lib/sparql.js:12:32)
    at ActorQueryOperationSparqlEndpoint.run (/Users/rtaelman/.config/yarn/global/node_modules/@comunica/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.js:46:41)
```

**Comment by joachimvh** [comment] 2020-03-19 10:12
This is caused by the order of the construct and slice operators in the algebra being different than those of the project and slice operators (in the case of a select). The solution will depend on what the correct result is for `CONSTRUCT { ?s ?p ?o. ?s ?p ?o } WHERE { ?s ?p ?o } LIMIT 100`. Specifically if that should return 100 or 200 triples. Going to look for the answer in the specs but please let me know should you already know the answer there :D

**Comment by joachimvh** [comment] 2020-03-19 10:43
The answer is 100, so I can add a fix to the sparql algebra for this.

**Comment by joachimvh** [comment] 2020-03-19 10:58
Fixed in SparqlAlgebra.js v2.2.1

**Comment by sdevalk** [comment] 2020-03-19 14:18
@joachimvh Thanks for the fix!

I've installed version 2.2.1 of sparqlalgebrajs.

The previous TypeError (`Cannot read property '0' of undefined`), mentioned in the comment of @rubensworks, is now gone - perfect!

However, if I run the command again...

```
comunica-sparql sparql@https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100"
```

...then it exits with the following message: `Error: Unknown SPARQL results content type: text/plain`.

If I debug the command...

```
comunica-sparql -l debug sparql@https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100"
```

...then the following log line appears:

```
INFO: Requesting https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%0A%20%20CONSTRUCT%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D%0A%20%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D%0A%20%20LIMIT%20100%0A%7D
```

The `query`, URL decoded, looks like this:

```
SELECT ?s ?p ?o WHERE {
  CONSTRUCT { ?s ?p ?o. }
  WHERE { ?s ?p ?o. }
  LIMIT 100
}
```

...which is not a valid query:

```
Virtuoso 37000 Error SP030: SPARQL compiler, line 4: syntax error at 'CONSTRUCT' before '{'
```

Do you know how this can be solved?

**Comment by rubensworks** [comment] 2020-03-19 14:22
It looks like we assumed in [`ActorQueryOperationSparqlEndpoint`](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.ts) that queries will always be SELECT queries, which obviously fails here due to the CONSTRUCT query.

So it looks like some small changes will need to be made here: the actor will need to handle 3 cases (select, construct, ask).

**Comment by sdevalk** [comment] 2020-03-19 16:40
Thanks for the update, @rubensworks!

**Comment by sdevalk** [comment] 2020-03-19 20:26
The upgrade to version 2.2.1 of `sparqlalgebrajs` appears to have a side effect.

For example, with version 2.2.0 the command underneath...

```
comunica-sparql https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/fragments -q "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 5"
```

...produces a bunch of triples. However, with version 2.2.1 the same command produces an error:

```
Error: Invalid query output type: Expected 'bindings' but got 'quads'
```

Any idea?

**Comment by rubensworks** [comment] 2020-03-20 06:22
@sdevalk This appears to be caused by the same problem I mentioned above. So this will require some changes in `ActorQueryOperationSparqlEndpoint`.

**Comment by sdevalk** [comment] 2020-03-20 08:32
@rubensworks Thanks for the clarification! To be sure: in the example above I'm not querying a SPARQL endpoint but a fragments endpoint (which used to work with `sparqlalgebrajs` v2.2.0).

**Comment by joachimvh** [comment] 2020-03-20 08:36
From having a quick the problem seems to be similar. The [slice actor](https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-slice/lib/ActorQueryOperationSlice.ts) which handles the LIMIT seems to be expecting a stream of bindings while the the result is (now) a stream of triples.

**Comment by rubensworks** [comment] 2020-03-20 11:43
@sdevalk Could you check out the master branch and try out if this fixes your problems?

**Comment by sdevalk** [comment] 2020-03-20 12:56
@rubensworks I've checked out the master branch. My findings:

1. Querying a fragments endpoint now produces the expected results again, a number of triples instead of an error:

```
comunica-sparql -l debug https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/fragments -q "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 5"
```

2. Querying a SPARQL endpoint still produces an error, though:

```
comunica-sparql -l debug sparql@https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 5"
```

Message: `Error: Unknown SPARQL results content type: text/plain`.

**Comment by rubensworks** [comment] 2020-03-23 07:58
I just had a look at the request logs, and it looks like this query is being sent to the endpoint:

```
SELECT ?s ?p ?o WHERE {
  CONSTRUCT { ?s ?p ?o. }
  WHERE { ?s ?p ?o. }
  LIMIT 5
```

Obviously, this is an invalid query.
I would expect the CONSTRUCT clause not to be sent to the endpoint, and construction happening client-side.

@joachimvh could you follow up on this?

**Comment by joachimvh** [comment] 2020-03-23 08:00
I'll try to have a look today

**Closed** 2020-03-27 12:20 UTC
Labels: bug

**Comment by rubensworks** [comment] 2020-03-27 12:22
@sdevalk I just tried out your query after the latest fix, and things are now working as intended.
Feel free to try out on master. A new Comunica version will be released early next week.

**Comment by sdevalk** [comment] 2020-03-28 16:17
@rubensworks Thanks! I've tried it on master - and it works perfectly now! Looking forward to the new Comunica release.
