### ISSUE TITLE
"end" event not called when number of results less than LIMIT

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#1168] opened 2023-03-09 19:22 UTC
#### Issue type:

- :bug: Bug 

____
#### Description:

When we execute this query

```sparql
  PREFIX foaf: <http://xmlns.com/foaf/0.1/>
  PREFIX schema: <http://schema.org/>
  SELECT *
  WHERE
  {
   ?id schema:name ?name;
       schema:abstract ?abstract;
       schema:contributor <https://data.knows.idlab.ugent.be/person/office/#>;
       schema:datePublished ?date;
       schema:author [
          foaf:name ?fName
       ].
  }
```

over these data sources

```javascript
[
  'https://data.knows.idlab.ugent.be/person/office/publications.ttl',
  'https://data.verborgh.org/ruben',
  'https://dylanvanassche.be/publications/',
  'https://hvdsomp.info/index.ttl' ,
  'https://data.knows.idlab.ugent.be/person/office/employees-extra',
  'https://julianrojas.org/'
    ]
```
the `end` event of the binding stream is not called.
When I add a limit then the `end` event is called only if the number of results is equal to the limit.
I wrote a script to test this:

```javascript
const QueryEngine = require('@comunica/query-sparql').QueryEngine;
const myEngine = new QueryEngine();

const args = process.argv.slice(2);
let limit = '';

if (args.length > 0) {
  limit = `\nLIMIT ${args[0]}`;
}

const query = `
  PREFIX foaf: <http://xmlns.com/foaf/0.1/>
  PREFIX schema: <http://schema.org/>
  SELECT *
  WHERE
  {
   ?id schema:name ?name;
       schema:abstract ?abstract;
       schema:contributor <https://data.knows.idlab.ugent.be/person/office/#>;
       schema:datePublished ?date;
       schema:author [
          foaf:name ?fName
       ].
  }
`

main(query);

async function main(query) {
  const bindingsStream = await myEngine.queryBindings(query + limit, {
    sources: [
      'https://data.knows.idlab.ugent.be/person/office/publications.ttl',
      'https://data.verborgh.org/ruben',
  'https://dylanvanassche.be/publications/',
  'https://hvdsomp.info/index.ttl' ,
  'https://data.knows.idlab.ugent.be/person/office/employees-extra',
      'https://julianrojas.org/'
    ],
  });

  let counter = 0;
  bindingsStream.on('data', (binding) => {
    console.error(binding.toString());
    counter ++;
    console.log(counter);
  });

  bindingsStream.on('end', () => {
    console.log('END: ' + counter);
  });

  bindingsStream.on('error', (error) => {
    console.error(error);
  });
}
```
You call the script via `node index.js [limit]` where `limit` is optional and is the LIMIT added to the query.

`node index.js` (no limit) never calls the `end` event. The script terminates though. Also the number of results (based on the counter) is not the same, while I would expect that to be always the same.
`node index.js 10` always calls the `end` event. The same for `node index.js 100`. But for `node index.js 1000` it doesn't anymore. And also for the latter the number of results is not always the same.
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.6.9 
| node             | v18.12.1
| npm              | 8.19.2
| yarn             | 1.22.5
| Operating System | darwin (Darwin 22.2.0)

If also tried it with Comunica `@comunica/query-sparql` v2.5.2, but the results are exactly the same.

**Comment by rubensworks** [comment] 2023-03-10 13:37
Probably related to #817

**Comment by rubensworks** [comment] 2023-05-25 12:23
Note to self: this seems to be caused by the caching inside RdfSourceQpf, as disabling that cache resolves the problem. (but we need the cache for performance reasons)

**Comment by rubensworks** [comment] 2023-07-10 05:42
This issue has been fixed in master.
But you should be able to make use of the fix by resetting your lockfile (asynciterator should be 3.8.1).

**Closed** 2023-07-10 05:48 UTC
Labels: bug 🐛, help-wanted, difficulty:high
