### ISSUE TITLE
Problems related to initialBindings

### ISSUE THREAD

**Issue by bergos** [comunica/comunica#1298] opened 2023-12-17 22:37 UTC
#### Issue type:

- :bug: Bug

____
#### Description:

I plan to use Comunica for SPARQL support in [shacl-engine](https://github.com/rdf-ext/shacl-engine). While running tests from the official test suite, I came across a few issues related to `initialBindings`. I created a repository with examples to reproduce the problem. There is a comment on top of each file with more details.

[Repository with examples](https://github.com/bergos/comunica-tests)

**Comment by rubensworks** [comment] 2023-12-18 07:20
Thanks for reporting these findings @bergos!

@joachimvh I suspect this is similar to recent issues you fixed in the algebra (#1223 and #1294). Could you check if this is something that needs changes in the algebra? If not, I can have a closer look to see if changes are needed on the Comunica-side.

**Comment by joachimvh** [comment] 2024-01-04 10:16
> @joachimvh I suspect this is similar to recent issues you fixed in the algebra (#1223 and #1294). Could you check if this is something that needs changes in the algebra?

Note that for both those issues I didn't take the initial bindings into account. There already was an issue with the original query without adding bindings when converting to algebra and back to SPARQL. So I had a look here to see if there also was a similar issue. 

In this case the generated SPARQL query was the same as the original query (again without applying bindings), except for the one in `pre-binding-002`. There the output query is 

```sparql
SELECT ?this WHERE {
  FILTER("false"^^<http://www.w3.org/2001/XMLSchema#boolean> 
         && (?this = <http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#InvalidResource>))
}
```

So probably for that one there is a bug in the algebra where the filter scope gets pulled out of their group graph patterns and applied to a higher level. Tbh, reading the spec on this again, this is probably a misinterpretation I made when originally implementing this. I opened https://github.com/joachimvh/SPARQLAlgebra.js/issues/105 for this.

But so for all the other ones I wouldn't know what the cause is. I didn't look into the effect of applying the bindings as I'm not sure how this works in Comunica. Is the query itself changed or is this applied afterwards?

**Comment by rubensworks** [comment] 2024-01-08 13:59
> So probably for that one there is a bug in the algebra where the filter scope gets pulled out of their group graph patterns and applied to a higher level. Tbh, reading the spec on this again, this is probably a misinterpretation I made when originally implementing this. I opened https://github.com/joachimvh/SPARQLAlgebra.js/issues/105 for this.

Thanks! :-)

> But so for all the other ones I wouldn't know what the cause is. I didn't look into the effect of applying the bindings as I'm not sure how this works in Comunica. Is the query itself changed or is this applied afterwards?

The handling of the initial bindings is done [here](https://github.com/comunica/comunica/blob/master/packages/bus-query-operation/lib/Bindings.ts#L45-L58), so mostly non-sparqlalgebrajs code indeed.

**Comment by simonvbrae** [comment] 2024-04-17 09:38
As discussed with @rubensworks, I will work on this issue.

**Comment by simonvbrae** [comment] 2024-04-17 10:55
What is the expected behaviour of the second filter expression in this query (taken from example pre-binding-002.js) when the InitialBinding for this has the value 'InvalidResource'? @bergos
```
PREFIX ex: <http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#>
    SELECT $this WHERE {
      {
        FILTER (false) .
      } UNION {
        FILTER ($this = ex:InvalidResource) .
      }
    }
```

**Comment by bergos** [comment] 2024-04-19 08:01
@simonvbrae The first part of the union is empty, and the second one returns one row with `$this` bound to `ex:InvalidResource`, which would also be the final result set.

**Comment by simonvbrae** [comment] 2024-04-21 16:49
> @simonvbrae The first part of the union is empty, and the second one returns one row with `$this` bound to `ex:InvalidResource`, which would also be the final result set.

Thank you for your reply! I have solved a couple of your examples including the query I mentioned above.
How about the query1 and query2 examples, what exactly is expected there? I'm not sure if the filter clause should be applied to the values, meaning after, which would result in the values being ignored.
For reference, query1 and query2:
```
  PREFIX ex: <http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#>
  SELECT $this $that WHERE {
    {
      VALUES $that { "test1" }
      FILTER (false) .
    } UNION {
      VALUES $that { "test2" }
      FILTER ($this = ex:InvalidResource) .
    }
  }
  ```
  ```PREFIX ex: <http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#>
  SELECT $this $that WHERE {
    {
      VALUES ($that) { ("test1") }
      FILTER (false) .
    } UNION {
      VALUES ($that) { ("test2") }
      FILTER ($this = ex:InvalidResource) .
    }
  }
  ```

**Comment by bergos** [comment] 2024-04-23 07:25
@simonvbrae In both cases, I would expect a single row with `$that = "test2"` and `$this = ex:InvalidResource`.

However, while the other examples are from the official SHACL test suite, I built these two by myself, and I'm not 100% sure how `VALUES` and initial bindings should interact. These examples were mainly included to help trace the issue. I noticed that the engine behaved differently for initial bindings than patterns matching triples in the data graph or values injected with the `VALUES` keyword.

**Comment by simonvbrae** [comment] 2024-06-26 10:34
@bergos I'm confused as to what is the intended result of this query, should it return `?x=1 and ?z=3` or only `?z=3`?:
```
const queryTestSelectStar = `PREFIX ex: <http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#>
    SELECT * WHERE {
      VALUES ?z { "3" }
      FILTER (?x="1" && ?z="3") .
    }`;
```
```
const initialBindings = bindingsFactory.bindings([
    [rdf.variable('this'), rdf.namedNode('http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#InvalidResource')],
    [rdf.variable('x'), rdf.literal('1')],
    [rdf.variable('y'), rdf.literal('2')],
  ]);
```
```
const dataset = await rdf.io.dataset.fromText('text/turtle', `
  @prefix ex: <http://datashapes.org/sh/tests/sparql/pre-binding/pre-binding-002.test#> .
  @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
  @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

  ex:ValidResource1 rdf:type rdfs:Resource.
  `);
```

**Comment by bergos** [comment] 2024-06-27 19:42
@simonvbrae I think it should be only `z=3` and that's also what Jena returns.

**Comment by rubensworks** [comment] 2024-06-28 13:08
> I would think having x=1 in the initialBindings leads to it being returned when using SELECT *. Or maybe not, maybe only variables explicitly appearing in the query should be returned? Maybe @rubensworks can shed some light on this.

I don't have a strong opinion on this, since this is not standardized in SPARQL, and it only applies to the `SELECT *` case.
But what Jena returns makes sense (only the selected variables before initial bindings are applied),
but what @simonvbrae expects also makes sense (also select the variables included in the initial bindings).

@simonvbrae For consistency, I'd say we do the same thing as Jena. But if it complicates the implementation too much, I guess we can deviate.

@bergos Would it complicate things a lot on your end if Comunica would deviate from Jena?

**Comment by simonvbrae** [comment] 2024-06-28 15:27
> > I would think having x=1 in the initialBindings leads to it being returned when using SELECT *. Or maybe not, maybe only variables explicitly appearing in the query should be returned? Maybe @rubensworks can shed some light on this.
> what @simonvbrae expects also makes sense (also select the variables included in the initial bindings).
> 
> @simonvbrae For consistency, I'd say we do the same thing as Jena. But if it complicates the implementation too much, I guess we can deviate.

My current fix returns the same as Jena so it's no problem.

**Closed** 2024-07-09 06:50 UTC
Labels: bug 🐛, in-progress
