### ISSUE TITLE
SPARQL ASK over single SPARQL endpoint fails

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#620] opened 2020-03-13 13:18 UTC
#### Issue type:

- :bug: Bug

____
#### Description:

When I execute an ASK query over a SPARQL endpoint (Stardog v6.2.2) and a TTL file, I get a correct response (the ASK correctly checks if the pattern is available in the Stardog db), but when I only query the SPARQL endpoint, I get an error `Unknown SPARQL results content type: application/json`

____
#### Environment:

- tested in  `comunica-sparql` v1.9.4 command line and v1.9.4/1.10/latest CDN via simple front end web app
- Windows 10
- Node v10.15.3

#### Crash log:

```
[2020-03-13T13:06:33.475Z]  INFO: Requesting http://localhost:5820/mydb/query?query=SELECT%20%3Fs%20%3Fp%20%3Fo%20WHERE%20%7B%20ASK%20WHERE%20%7B%20%3Fs%20%3Fp%20%3Fo.%20%7D%20%7D { actor:
   'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher' }
[(node:11492) UnhandledPromiseRejectionWarning: Error: Unknown SPARQL results content type: application/json
    at SparqlEndpointFetcher.<anonymous> (C:\Users\user.name\AppData\Roaming\nvm-new\v10.15.3\node_modules\@comunica\actor-init-sparql\node_modules\fetch-sparql-endpoint\lib\SparqlEndpointFetcher.js:64:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user.name\AppData\Roaming\nvm-new\v10.15.3\node_modules\@comunica\actor-init-sparql\node_modules\fetch-sparql-endpoint\lib\SparqlEndpointFetcher.js:4:58)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:11492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rubensworks** [comment] 2020-03-13 13:20
This appears to be a duplicate of #535.
(Moved this issue there)

**Closed by rubensworks** 2020-03-13 13:20 UTC
