### ISSUE TITLE
query-sparql query rewrite problems with `InitialBindings`

### ISSUE THREAD

**Issue by qjhart** [comunica/comunica#1223] opened 2023-06-28 19:15 UTC
#### Issue type:

- :bug: Bug 

____
#### Description:
 

I have two seperate, but related issues when using initalBindings on queries.  In some cases blocks are rewritten out of order, and some queries throw an error when parsing some  combinations

The example shows a service query being rewritten, and a graph/filter combination failing.

```js
import { QueryEngine } from '@comunica/query-sparql';
const myEngine = new QueryEngine();
import { BindingsFactory } from '@comunica/bindings-factory';
import { DataFactory } from 'rdf-data-factory';

const DF = new DataFactory();
const BF = new BindingsFactory();

const service_q=`
select * WHERE {
  service <http://localhost:3030/experts/sparql> {
    graph <http://iam.ucdavis.edu> {
    ?s ?p ?o.
  }}}`

const graph_ok1 =`
select ?s
WHERE {
  graph <http://graph.ucdavis.edu/> {
    ?s ?p ?o.
#    filter(regex(str(?s),'#'))
  }
  GRAPH <http://other.ucdavis.edu/> {
    ?s ?p  ?o.
}
}
`

const graph_ok2 =`
select ?s
WHERE {
  graph <http://graph.ucdavis.edu/> {
    ?s ?p ?o.
    filter(regex(str(?s),'#'))
  }
#  GRAPH <http://other.ucdavis.edu/> {
#    ?s ?p  ?o.
#}
}
`

const graph_bad =`
select ?s
WHERE {
  graph <http://graph.ucdavis.edu/> {
    ?s ?p ?o.
    filter(uri(?s))
  }
  GRAPH <http://other.ucdavis.edu/> {
    ?s ?p  ?o.
}
}
`


const context= { sources: ['http://localhost:3030/experts/sparql'] };

// https://comunica.dev/docs/query/advanced/context/
const bindings = { initialBindings:
                   BF.fromRecord({
                     o: DF.literal('foo')
                   }) }

//const q1 = await myEngine.queryBindings(service_q, context);
myEngine.queryBindings(service_q, {...bindings, ...context });

/* Quereies the service with: 
SELECT ?p ?s WHERE { 
  GRAPH <http://iam.ucdavis.edu> { 
    SERVICE <http://localhost:3030/experts/sparql> { ?s ?p "foo". } } }
*/


//myEngine.queryBindings(graph_ok1, {...bindings, ...context });
//myEngine.queryBindings(graph_ok2, {...bindings, ...context });
myEngine.queryBindings(graph_bad, {...bindings, ...context });

/* FAILS WITH  (see log below)

./query_example/node_modules/sparqlalgebrajs/lib/sparql.js:787
    if (name.value.length === 0)
             ^
*/
```
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.7.1
| node             | v18.13.0
| npm              | 9.5.1
| yarn             | _Yarn is unavailable_
| Operating System | linux (Linux 6.1.0-9-amd64)

#### Crash log:

[Error Log](https://pastebin.com/hxm8EeGp)

**Comment by simonvbrae** [comment] 2023-11-17 12:08
The issue, which was caused by sparqlalgebra not removing quads correctly when joining graph blocks should be fixed in the following PR: https://github.com/joachimvh/SPARQLAlgebra.js/pull/103.

**Comment by rubensworks** [comment] 2023-11-21 09:07
Nice!

**Closed by rubensworks** 2023-11-21 09:07 UTC
Labels: bug 🐛

**Comment by qjhart** [comment] 2023-11-29 00:39
Wouldn't the sparqlalgebra minimum version need to be updated for this to be closed?

**Comment by qjhart** [comment] 2023-11-29 01:04
Hmm, I think that I probably shouldn't have put two issues together.  The second issue seems to be resolved, but the first issue:

```js
import { QueryEngine } from '@comunica/query-sparql';
const myEngine = new QueryEngine();
import { BindingsFactory } from '@comunica/bindings-factory';
import { DataFactory } from 'rdf-data-factory';

const DF = new DataFactory();
const BF = new BindingsFactory();

const service_q=`
select * WHERE {
  service <http://localhost:3030/experts/sparql> {
    graph <http://iam.ucdavis.edu> {
    ?s ?p ?o.
  }}}`


const context= { sources: ['http://localhost:3030/experts/sparql'] };

// https://comunica.dev/docs/query/advanced/context/
const bindings = { initialBindings:
                   BF.fromRecord({
                     o: DF.literal('foo')
                   }) }

//const q1 = await myEngine.queryBindings(service_q, context);
myEngine.queryBindings(service_q, {...bindings, ...context });
```
Still transposes the service and graph components, and rewrites the the query as : 

``` sparql
SELECT ?p ?s WHERE {
  GRAPH <http://iam.ucdavis.edu> {
    SERVICE <http://localhost:3030/experts/sparql> { ?s ?p "foo". } } }
```

**Comment by rubensworks** [comment] 2023-11-29 06:58
> Wouldn't the sparqlalgebra minimum version need to be updated for this to be closed?

It will be in the next comunica update, but for now, you can just reset your lockfile and re-install.

> Hmm, I think that I probably shouldn't have put two issues together. The second issue seems to be resolved, but the first issue:

Could you open a separate issue for this?
