### ISSUE TITLE
FILTER on langString literals does not work with N3 as source

### ISSUE THREAD

**Issue by gvanderh** [comunica/comunica#1146] opened 2023-01-31 07:42 UTC
```
// add a quad with a language string
const store = new N3.Store();
store.addQuad(namedNode('http://ex.com/s'), namedNode('http://ex.com/p'), literal('abc', 'en'));

// query it using SPARQL with a FILTER
const eng = new comunica.QueryEngine();
const bindings = await eng.queryBindings('SELECT ?o WHERE { ?s ?p ?o. FILTER(?o = "abc"@en) }', { sources: [ store ] });
```

Any FILTER on ?o in the example fails (with or without language string, = or !=). That is, as soon as a FILTER on the langString literal is present in the query, it won't return any results anymore. No crash or log warnings, just an empty result set.

Observed on Comunica v2.6.0 in combination with N3 v1.16.3.

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment] 2023-01-31 07:54
This is surprising, I thought we had spec tests for this.

**Comment by rubensworks** [comment] 2023-01-31 11:52
A bounty has been placed on this issue via the Comunica Association (see original post).

**Comment by danielbeeke** [comment] 2023-02-21 11:24
I have reproduced with the code in the description.

The logger shows:
```
[2023-02-21T11:17:47.764Z]  WARN: Error occurred while filtering. { error: { [Error: Equality test for literals with unsupported datatypes] args: [ LangStringLiteral { expressionType: 'term', typedValue: 'abc', dataType: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#langString', strValue: 'abc', language: 'en', termType: 'literal' }, LangStringLiteral { expressionType: 'term', typedValue: 'abc', dataType: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#langString', strValue: 'abc', language: 'en', termType: 'literal' } ] }, bindings: '{\n  "s": "http://ex.com/s",\n  "p": "http://ex.com/p",\n  "o": "\\"abc\\"@en"\n}', actor: 'urn:comunica:default:query-operation/actors#filter' }
```

That pointed me towards:

https://github.com/comunica/sparqlee/blob/master/lib/functions/RegularFunctions.ts#L111

That looks kind of odd to me.
When I remove the throw Error, it works. But there probably is a reason why Sparqlee does not want to check literals.

**Comment by danielbeeke** [comment] 2023-02-21 11:50
Could this be related?

https://github.com/comunica/sparqlee/issues/2

**Comment by rubensworks** [comment] 2023-02-22 13:20
@jitsedesmet Do you have any thoughts on the findings of @danielbeeke?

**Comment by danielbeeke** [comment] 2023-02-23 14:51
I think it should be possible to check against Literals
See: https://www.w3.org/TR/rdf-concepts/#section-Literal-Equality

Also the equality check also happens in the Term itself.

**Comment by jitsedesmet** [comment] 2023-02-23 15:55
I think this is an error in the code.
Like you said, this line throws the error: https://github.com/comunica/sparqlee/blob/master/lib/functions/RegularFunctions.ts#L111
And the error it throws is: https://github.com/comunica/sparqlee/blob/master/lib/util/Errors.ts#L69
It looks like the provided link there: https://www.w3.org/TR/sparql11-query/#func-RDFterm-equal
doesn't seem to be implemented correctly? The error should only be thrown if the literals are not the same.

> Returns TRUE if term1 and term2 are the same RDF term as defined in [Resource Description Framework (RDF): Concepts and Abstract Syntax](http://www.w3.org/TR/rdf-concepts/) [[CONCEPTS](https://www.w3.org/TR/sparql11-query/#CONCEPTS)]; produces a type error if the arguments are both literal but are not the same RDF term [*](https://www.w3.org/TR/sparql11-query/#func-RDFterm-equal-foot1); returns FALSE otherwise.

**Comment by danielbeeke** [comment] 2023-02-23 21:38
Great, same findings as me, I created PR to fix it.

**Comment by jeswr** [comment] 2023-03-23 00:08
Not sure this is fully resolved - see https://github.com/comunica/comunica/discussions/1182#discussioncomment-5399194.

**Comment by rubensworks** [comment] 2023-03-23 05:36
Might be better to create a separate issue for this. This issue is about the equality operator, while the new one seems to be about `IN`.

**Comment by jeswr** [comment] 2023-03-23 09:12
Closing in favour of #1185

**Closed by jeswr** 2023-03-23 09:12 UTC
Labels: bug 🐛, difficulty:low, effort:low, comunica-association-bounty
