### ISSUE TITLE
Querying over some SPARQL endpoints only returns triples in service description

### ISSUE THREAD

**Issue by mathib** [comunica/comunica#619] opened 2020-03-13 13:00 UTC
#### Issue type:

- :bug: Bug

____
#### Description:

Hi! I'm seeing weird behavior when querying a SPARQL endpoint (Stardog v6.2.2) using the CDN ([http://rdf.js.org/comunica-browser/versions/1.9.4/packages/actor-init-sparql/comunica-browser.js](http://rdf.js.org/comunica-browser/versions/1.9.4/packages/actor-init-sparql/comunica-browser.js)).

- Test 1: `comunica-sparql` v1.9.4 (command line) using node v10.15.3
   - query works fine and returns the triples of both sources
- Test 2: using `actor-init-sparql` CDN v1.9.4 and 1.10/latest in a simple JS web app (only client side)
   - query over both sources returns the triples of the TTL file and triples describing the SPARQL endpoint
   - query over only the SPARQL endpoint returns the triples stored in its default graph correctly
- Test 3: using `actor-init-sparql` CDN v1.9.4 and 1.10/latest in the same simple JS web app as test 2, but executed JS in the browser console
   - query over both sources returns the triples of the TTL file and triples describing the SPARQL endpoint
   -  query over only the SPARQL endpoint returns the triples describing the SPARQL endpoint

With "triples describing the SPARQL endpoint", I mean triples such as:

b0_bnode5f47905ed65fe4745f4ada5fa3415fd7abc37414085f14091 | http://www.w3.org/ns/sparql-service-description#supportedLanguage | http://www.w3.org/ns/sparql-service-description#SPARQL11Query
-- | -- | --
b0_bnode5f47905ed65fe4745f4ada5fa3415fd7abc37414085f14093 | http://www.w3.org/ns/sparql-service-description#defaultEntailmentRegime | http://www.w3.org/ns/entailment/OWL-Direct
b0_bnode5f47905ed65fe4745f4ada5fa3415fd7abc37414085f14095 | http://www.w3.org/ns/sparql-service-description#resultFormat | http://www.w3.org/ns/formats/SPARQL_Results_TSV
... | ... | ...

____
#### Environment:

* all tests done in Windows 10
* simple SPARQL query used for testing: `PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * { ?s ?p ?o }`
* a handful of triples stored in a Stardog db
* a handful of triples stored in a separate TTL file
* Versions of Comunica tested:
   - `actor-init-sparql` CDN: v1.9.4 and v1.10/latest
   - ` comunica-sparql` v1.9.4 (command line)

**Comment by rubensworks** [comment] 2020-03-13 13:09
This seems to be related to #535.

@mathib Is your Stardog endpoint by any chance public, so I can use it for debugging?

**Comment by rubensworks** [comment] 2020-03-13 13:37
I've added a note in the README:

> Some SPARQL endpoints may be recognised as a file instead of a SPARQL endpoint due to them not supporting SPARQL Service Description, which may produce incorrect results. For these cases, the sparql type MUST be set.

@mathib Can you check if this works for you?

**Comment by mathib** [comment] 2020-03-13 13:48
@rubensworks : sorry, I'm afraid not. I don't have the means (and knowledge) to set up the triplestore on a public server :/

Some other issue I've seen and maybe related to this one, was when I was querying the TTL of my ontology via its namespace https://w3id.org/fog#. When I make a custom HTTP request (e.g. using Postman) to the namespace, I can request the TTL by setting an Accept header (it then follows the [w3id redirect](https://github.com/perma-id/w3id.org/blob/master/fog/.htaccess) to a raw github TTL file). However, when I enter the namespace as a source for Comunica ( tested using the command line `comunica-sparql` v1.9.4, but saw it in the past also when using the CDN in a web app), it only queries the triples (json-ld) embedded in the HTML page automatically generated by [Widoco](https://github.com/dgarijo/Widoco). It looks like Comunica sees two RDF datasets, and just selects one randomly (either the "metadata/endpoint description" triples or the "actual content" triples).

**Comment by mathib** [comment] 2020-03-13 13:49
> I've added a note in the README:
> 
> > Some SPARQL endpoints may be recognised as a file instead of a SPARQL endpoint due to them not supporting SPARQL Service Description, which may produce incorrect results. For these cases, the sparql type MUST be set.
> 
> @mathib Can you check if this works for you?

I always set the source type to SPARQL (both in the web app and in the command line)...

**Comment by rubensworks** [comment] 2020-03-13 13:58
> I always set the source type to "sparql" (both in the web app and in the command line) when it's a SPARQL endpoint...

I just tested this myself with different public SPARQL endpoints (Virtuoso, Fuseki, GraphDB), and all of those work fine. I couldn't find one for Stardog, and since I don't have a license for it, so I'm a bit blocked on this.

> Some other issue I've seen and maybe related to this one, was when I was querying the TTL of my ontology via its namespace https://w3id.org/fog#. 

This is a different issue, it appears to be caused by your server performing incorrect content negotiation. Comunica always prefers Turtle over HTML. However, your server always seems to return HTML once it has been mentioned in the Accept header.

For instance, the following returns HTML, while it should return Turtle:

```
curl -H'Accept: text/turtle,text/html;q=0.5' -L https://w3id.org/fog#
```

**Comment by mathib** [comment] 2020-03-13 16:22
> > I always set the source type to "sparql" (both in the web app and in the command line) when it's a SPARQL endpoint...
> 
> I just tested this myself with different public SPARQL endpoints (Virtuoso, Fuseki, GraphDB), and all of those work fine. I couldn't find one for Stardog, and since I don't have a license for it, so I'm a bit blocked on this.

Stardog has a free academic edition. 
Alternatively, I can try to help debugging from my side. Any ideas where to start looking? I'm just puzzled that it works for with comunica on the command line, but not when using the CDN. Should be the same, right?

> This is a different issue, it appears to be caused by your server performing incorrect content negotiation. Comunica always prefers Turtle over HTML. However, your server always seems to return HTML once it has been mentioned in the Accept header.
> 
> For instance, the following returns HTML, while it should return Turtle:
> 
> ```
> curl -H'Accept: text/turtle,text/html;q=0.5' -L https://w3id.org/fog#
> ```
 Aha, then it's probably some issue with my redirects in .htaccess

**Comment by rubensworks** [comment] 2020-03-13 17:01
> Alternatively, I can try to help debugging from my side. Any ideas where to start looking? I'm just puzzled that it works for with comunica on the command line, but not when using the CDN. Should be the same, right?

It may have something to do with the Accept headers. Due to CORS issues, Comunica will limit the Accept header to 128 characters when running in browsers. On the CLI, a longer Accept header will be sent.

So checking the actual requests that are sent might be a good place to start.

**Comment by rubensworks** [comment] 2020-03-23 14:57
Part of this will be fixed in #633.

I'm leaving this issue open for the Stardog-specific bug.

**Comment by rubensworks** [comment] 2020-03-25 12:29
The Stardog problem has been identified, and will be fixed in the next Comunica release.

**Closed by rubensworks** 2020-03-25 12:29 UTC
Labels: bug, major

**Comment by mathib** [comment] 2020-04-02 10:44
Hi @rubensworks, I would love to test this. When do you plan to upload the new Comunica version to a CDN? I think `http://rdf.js.org/comunica-browser/versions/latest/packages/actor-init-sparql/comunica-browser.js` still points to v1.10.0?

**Comment by rubensworks** [comment] 2020-04-02 10:48
It looks like the CDN deployment is not working anymore.
Following up in #647.
