### ISSUE TITLE
Feature: Provide custom http cache as context entry

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1073] opened 2022-09-20 13:59 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

To allow multiple engines to share the same http cache it would be useful to have a httpCache as an optional Comunica entry. This would also allow things like preloading of webpages.

____

**Comment by rubensworks** [comment] 2022-09-20 14:01
Duplicate of #166?
This is being implemented in #1010.

**Comment by rubensworks** [comment] 2022-09-20 14:34
> I think they are different issues. This issue is to allow users to provide an instantiated http-cache as a context entry to, for instance, allow users to pass a preloaded cache into the engine; or to allow different instantiations of the different engine configurations to share the same cache.

That's what we had in mind indeed as use case for #166.

See the sentence "This new actor should be able to use a [Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache) from the context...".

> As far I understand https://github.com/comunica/comunica/pull/1010 does not include such a context key

Not yet, but it [should](https://github.com/comunica/comunica/pull/1010#discussion_r963640543).

**Closed** 2022-09-20 14:53 UTC
Labels: feature ➕
