### ISSUE TITLE
Add support for tree ontology

### ISSUE THREAD

**Issue by SanderVanhove** [comunica/comunica#295] opened 2018-10-08 14:52 UTC
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

The ability to resolve queries over a dataset defined by the [Tree Ontology](https://github.com/pietercolpaert/TreeOntology).

This includes:
* Pagination over a tree
* Applying filters that follow certain branches

Could be done by including a new query operation tree filter actor that indicates that we are working with a tree ontology in the context and a RDF resolve quad pattern tree actor that solves the query over the tree.

**Comment by pietercolpaert** [comment] 2018-10-08 16:28
Also don’t forget this is also relevant for the ORDER actor. Motivating example:

```sparql
SELECT ?person ?date
WHERE {
  <https://ruben.verborgh.org/profile#me> dbpedia-owl:birthPlace ?place;
           dbpedia-owl:birthDate  ?dateR.
  ?person  dbpedia-owl:birthPlace ?place;
           dbpedia-owl:birthDate  ?date.
  FILTER(?date > ?dateR)
} ORDER BY ?date DESC
```

When there would a Tree exposed for a hydra:Collection managing Persons, indexed on the predicate dbpedia-owl:birthDate, then the AsyncIterator of the result could immediately start at the youngest person on Wikipedia and immediately return a result, instead of still having to go through the list of all persons on Wikpedia.

**Comment by rubensworks** [comment] 2022-11-09 12:17
Duplicate of #1054

**Closed by rubensworks** 2022-11-09 12:17 UTC
Labels: feature ➕, difficulty:high, effort:high
