### ISSUE TITLE
comunica-sparql-http can fail to start on Windows

### ISSUE THREAD

**Issue by kabulkurniawan** [comunica/comunica#616] opened 2020-03-10 09:33 UTC
#### Issue type:

- :bug: Bug

____
#### Description:
I tried to follow this Comunica tutorial [1] and got an error while exposing rdf file as sparql-endpoint using comunica-sparql-http

[1]: https://github.com/comunica/Tutorial-Comunica-Querying-Data/wiki/Comunica-tutorial:-Querying-Data

____
#### Environment:
command: 
comunica-sparql-http "{ \"sources\": [{ \"type\": \"file\", \"value\" : \"http://localhost:8080/data.jsonld\" }]}"

I used Windows 10 OS with nodejs version v12.14.1
the rdf file located was http://localhost:8080/data.jsonld was running well
 
#### Crash log:
 UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:272:10)
    at WriteStream.Writable.write (_stream_writable.js:307:21)
    at C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\lib\HttpServiceSparqlEndpoint.js:45:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rubensworks** [comment] 2020-03-10 13:47
So it looks like the server fails to start for some reason, but due to a bug, the error handling fails, so you don't see the actual error.

I *think* the problem may be related to port binding. Perhaps port 8080 is already bound on your machine, so you could try changing it.

Note to self: the error seems to be on this line: https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/lib/HttpServiceSparqlEndpoint.ts#L81

**Comment by kabulkurniawan** [comment] 2020-03-10 14:12
> So it looks like the server fails to start for some reason, but due to a bug, the error handling fails, so you don't see the actual error.
> 
> I _think_ the problem may be related to port binding. Perhaps port 8080 is already bound on your machine, so you could try changing it.
> 
> Note to self: the error seems to be on this line: https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/lib/HttpServiceSparqlEndpoint.ts#L81

I've changed the port but the problem still the same...

**Comment by rubensworks** [comment] 2020-03-10 14:23
Then it will be hard to figure out the problem...

Could you open `C:\Users\KKurniawan\AppData\Roaming\npm\node_modules@comunica\actor-init-sparql\lib\HttpServiceSparqlEndpoint.js`, and _before_ line 45, add `console.log(reason)`?
That should show you some additional information about the error just before it crashes.

**Comment by kabulkurniawan** [comment] 2020-03-10 14:40
> Then it will be harder to figure out the problem...
> 
> Could you open `C:\Users\KKurniawan\AppData\Roaming\npm\node_modules@comunica\actor-init-sparql\lib\HttpServiceSparqlEndpoint.js`, and _before_ line 45, add `console.log(reason)`?
> That should show you some additional information about the error just before it crashes.
this one:

Error: Invalid components file "C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\components\C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\components\components.jsonld":
Error: ENOENT: no such file or directory, open 'D:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\components\components.jsonld'
    at Function.addFilePathToError (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\componentsjs\lib\Util.js:542:16)
    at RdfStreamParser.<anonymous> (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\componentsjs\lib\Util.js:80:58)
    at RdfStreamParser.emit (events.js:223:5)
    at ReadStream.<anonymous> (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\componentsjs\lib\rdf\RdfStreamParser.js:18:40)
    at ReadStream.emit (events.js:228:7)
    at internal/fs/streams.js:120:12
    at FSReqCallback.oncomplete (fs.js:146:23)
(node:9792) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:272:10)
    at WriteStream.Writable.write (_stream_writable.js:307:21)
    at C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\lib\HttpServiceSparqlEndpoint.js:46:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:9792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rubensworks** [comment] 2020-03-10 15:15
This part seems to be the relevant part (incorrect path creation):

> 'D:\Users\KKurniawan\AppData\Roaming\npm\node_modules@comunica\actor-init-sparql\components\components.jsonld'

@joachimvh Have you encountered this Windows-specific problem before?

**Comment by joachimvh** [comment] 2020-03-11 08:17
I think I've seen it once in the past but don't remember why anymore. Recently one of @brechtvdv students had a similar issue. Maybe he knows what happened there?

**Comment by rubensworks** [comment] 2020-03-11 08:30
Oh, so this was a known issue 😞 

@joachimvh Can you look into this one?
The problem seems to be caused by an invalid module path concat (`+` is used instead of `path.join)`. I suspect the problem exists in `bin/`, `HttpServiceSparqlEndpoint.ts` or Components.js.

**Comment by dreeki** [comment] 2020-03-11 10:49
@rubensworks @joachimvh @kabulkurniawan I had this issue aswel. I'm not entirely sure what caused the error, but I managed to get rid of it by using an older version of node. At the time, I was at version 13.8.0 and I changed to 12.16.1 or 10.19.0. I'm not sure which of those it was (it's been a while). If you don't know how to change your node version (or want an easy alternative to switch between versions), you should have a look at https://github.com/tj/n.

**Comment by kabulkurniawan** [comment] 2020-03-11 13:42
I finally skip this error by using docker with ubuntu platform and it's work.
a question, when I run :

[1] comunica-sparql-http "{ \"sources\": [{ \"type\": \"file\", \"value\" : \"http://localhost:8080/data.jsonld\" }]}"

I can get data by requesting 

[2] http://localhost:3000/sparql?query=SELECT * WHERE {?s ?p ?o}.

but when I update the source data (data.jsonld - modify with another turtle data) and I ask with the same query again [2] and the result remains the same as before I update it. It only changes when I restart the server [1].

Is it any possibility to get the data update without restarting the server [1]?

**Comment by kabulkurniawan** [comment] 2020-03-11 13:55
I also try to perform query over multiple LD-Interface including:

1. file (hosted at http://localhost:8080/data.jsonld)
2. LDF-server (http://localhost:5000)
3. dbpedia sparql (http://dbpedia.org/sparql)
4. SPARQL endpoint I've created using comunica (http://localhost:3000)

- first I perform to query over [1] and [2] using this CLI:
comunica-sparql http://localhost:8080/data.jsonld http://localhost:5000 -q "SELECT * WHERE {?s ?p ?o} LIMIT 10" => works fine!

- then I perform to query over [1] and [3] using this CLI:
comunica-sparql http://localhost:8080/data.jsonld http://dbpedia.org/sparql -q "SELECT * WHERE {?s ?p ?o} LIMIT 10" => works, no problem.

- but when I perform to query over [1] and [4] using this CLI:
comunica-sparql http://localhost:8080/data.jsonld http://localhost:3000 -q "SELECT * WHERE {?s ?p ?o} LIMIT 10" -> I got this error:
[Error: Could not retrieve http://localhost:3000 (404: unknown error)
    at ActorRdfDereferenceHttpParse.run (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\@comunica\actor-rdf-dereference-http-parse\lib\ActorRdfDereferenceHttpParseBase.js:56:27)
    at async MediatedLinkedRdfSourcesAsyncRdfIterator.getNextSource (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\@comunica\actor-rdf-resolve-quad-pattern-hypermedia\lib\MediatedLinkedRdfSourcesAsyncRdfIterator.js:44:38)
(node:2744) UnhandledPromiseRejectionWarning: Error: Could not retrieve http://localhost:3000 (404: unknown error)
    at ActorRdfDereferenceHttpParse.run (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\@comunica\actor-rdf-dereference-http-parse\lib\ActorRdfDereferenceHttpParseBase.js:56:27)
    at async MediatedLinkedRdfSourcesAsyncRdfIterator.getNextSource (C:\Users\KKurniawan\AppData\Roaming\npm\node_modules\@comunica\actor-init-sparql\node_modules\@comunica\actor-rdf-resolve-quad-pattern-hypermedia\lib\MediatedLinkedRdfSourcesAsyncRdfIterator.js:44:38)
(node:2744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:2744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

{"?s":"http://example.com/joachimvh","?p":"http://www.w3.org/2000/01/rdf-schema#label","?o":"\"Rijalul Ilmi\"@en"},
{"?s":"http://example.com/joachimvh","?p":"http://dbpedia.org/property/occupation","?o":"http://dbpedia.org/resource/Computer_scientist"},
{"?s":"http://www.rubensworks.net/#me","?p":"http://www.w3.org/2000/01/rdf-schema#label","?o":"\"Ruben Taelman\"@en"},
{"?s":"http://www.rubensworks.net/#me","?p":"http://dbpedia.org/property/occupation","?o":"http://dbpedia.org/resource/Computer_scientist"}

again, seems that we have a problem with comunica sparql http..

**Comment by rubensworks** [comment] 2020-03-11 14:47
@kabulkurniawan Those problems are unrelated to this issue. In the future, please create separate issues for them.

> Is it any possibility to get the data update without restarting the server [1]?

No, that is not possible at the moment. But you are welcome to submit a Pull Request implementing this feature.

> but when I perform to query over [1] and [4] using this CLI:

This is a know issue, see: https://github.com/comunica/comunica/issues/535

**Comment by kabulkurniawan** [comment] 2020-03-11 17:10
> @kabulkurniawan Those problems are unrelated to this issue. In the future, please create separate issues for them.
> 
> > Is it any possibility to get the data update without restarting the server [1]?
> 
> No, that is not possible at the moment. But you are welcome to submit a Pull Request implementing this feature.
That's would be good to have this feature, I will need it for my current project. is it that hard to add that feature?
> 
> > but when I perform to query over [1] and [4] using this CLI:
> 
> This is a know issue, see: #535
Oke, please let me know what you need to solve the problem and what can I do to solve it.

**Comment by rubensworks** [comment] 2020-03-12 07:45
> That's would be good to have this feature, I will need it for my current project. is it that hard to add that feature?

No, but this is not the place to discuss this. Please continue this discussion at #618.

> Oke, please let me know what you need to solve the problem and what I can do to solve it.

Please refer to #535.

**Comment by rubensworks** [comment] 2022-03-03 13:51
@joachimvh Could you check if this still happens in Comunica 2? If not, we can close this one.

**Comment by joachimvh** [comment] 2022-03-07 12:59
> @joachimvh Could you check if this still happens in Comunica 2? If not, we can close this one.

Can't say if it is fixed, but I don't have this problem when starting the server on Windows.

**Comment by rubensworks** [comment] 2022-03-07 13:43
Thanks for checking @joachimvh! Closing this then.

**Closed by rubensworks** 2022-03-07 13:43 UTC
Labels: bug 🐛, difficulty:medium, dev-ready, effort:medium
