### ISSUE TITLE
Only first page of Hydra paged collection returned

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#1180] opened 2023-03-20 20:24 UTC
#### Issue type:

- :bug: Bug 

____
#### Description:

Assume a paginated Turtle file at https://opendata.picturae.com/catalog.ttl?page=1. (This uses the legacy `hydra:PagedCollection` rather than the newer `hydra:PartialCollectionView`, but Comunica seems to support both.)

A query using two predicates returns the expected output (a count of **209** resources that are spread over 3 pages):

```shell
comunica-sparql -l debug 'https://opendata.picturae.com/catalog.ttl?page=1' 'select (count(?s) as ?c) {?s a <http://www.w3.org/ns/dcat#Dataset> ; <http://purl.org/dc/terms/identifier> ?i }'
[2023-03-20T20:20:18.029Z]  INFO: Requesting https://opendata.picturae.com/catalog.ttl?page=1 { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v18.14.1; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2023-03-20T20:20:19.118Z]  INFO: Identified as file source: https://opendata.picturae.com/catalog.ttl?page=1 { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }
[2023-03-20T20:20:19.134Z]  DEBUG: Determined physical join operator 'inner-bind' { entries: 2, variables: [ [ 's' ], [ 's', 'i' ] ], costs: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': 106100.40607586392, 'inner-hash': 213500, 'inner-symmetric-hash': 212600, 'inner-nested-loop': 222200, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined }, coefficients: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': { iterations: 0.3899427883167721, persistedItems: 0, blockingItems: 0, requestTime: 1061.000161330756 }, 'inner-hash': { iterations: 200, persistedItems: 100, blockingItems: 100, requestTime: 2122 }, 'inner-symmetric-hash': { iterations: 200, persistedItems: 200, blockingItems: 0, requestTime: 2122 }, 'inner-nested-loop': { iterations: 10000, persistedItems: 0, blockingItems: 0, requestTime: 2122 }, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined } }
[2023-03-20T20:20:19.135Z]  DEBUG: First entry for Bind Join:  { entry: Quad { termType: 'Quad', value: '', subject: Variable { termType: 'Variable', value: 's' }, predicate: NamedNode { termType: 'NamedNode', value: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' }, object: NamedNode { termType: 'NamedNode', value: 'http://www.w3.org/ns/dcat#Dataset' }, graph: DefaultGraph { termType: 'DefaultGraph', value: '' }, type: 'pattern' }, metadata: { requestTime: 1061, pageSize: 100, cardinality: { type: 'exact', value: 100 }, first: 'https://opendata.picturae.com/catalog.ttl?page=1', next: 'https://opendata.picturae.com/catalog.ttl?page=2', previous: null, last: 'https://opendata.picturae.com/catalog.ttl?page=3', searchForms: { values: [] }, canContainUndefs: false, order: undefined, availableOrders: undefined, variables: [ Variable { termType: 'Variable', value: 's' } ] }, actor: 'urn:comunica:default:rdf-join/actors#inner-multi-bind' }
[[2023-03-20T20:20:19.142Z]  INFO: Requesting https://opendata.picturae.com/catalog.ttl?page=2 { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v18.14.1; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2023-03-20T20:20:20.095Z]  INFO: Identified as file source: https://opendata.picturae.com/catalog.ttl?page=2 { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }
[2023-03-20T20:20:20.111Z]  INFO: Requesting https://opendata.picturae.com/catalog.ttl?page=3 { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v18.14.1; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2023-03-20T20:20:20.264Z]  INFO: Identified as file source: https://opendata.picturae.com/catalog.ttl?page=3 { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }

{"c":"\"209\"^^http://www.w3.org/2001/XMLSchema#integer"}
]
```

However, when adding a third predicate to the query (that all resources have), things fall apart:

```
comunica-sparql -l debug 'https://opendata.picturae.com/catalog.ttl?page=1' 'select (count(?s) as ?c) {?s a <http://www.w3.org/ns/dcat#Dataset> ; <http://purl.org/dc/terms/identifier> ?i; <http://purl.org/dc/terms/issued> ?issued }'
[2023-03-20T20:20:04.874Z]  INFO: Requesting https://opendata.picturae.com/catalog.ttl?page=1 { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v18.14.1; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2023-03-20T20:20:06.144Z]  INFO: Identified as file source: https://opendata.picturae.com/catalog.ttl?page=1 { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }
[2023-03-20T20:20:06.163Z]  DEBUG: Determined physical join operator 'inner-bind' { entries: 3, variables: [ [ 's' ], [ 's', 'i' ], [ 's', 'issued' ] ], costs: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': 124400.8555483328, 'inner-hash': undefined, 'inner-symmetric-hash': undefined, 'inner-nested-loop': undefined, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': 1373200 }, coefficients: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': { iterations: 0.7798855766335442, persistedItems: 0, blockingItems: 0, requestTime: 1244.0007566275617 }, 'inner-hash': undefined, 'inner-symmetric-hash': undefined, 'inner-nested-loop': undefined, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': { iterations: 1000000, persistedItems: 0, blockingItems: 0, requestTime: 3732 } } }
[2023-03-20T20:20:06.164Z]  DEBUG: First entry for Bind Join:  { entry: Quad { termType: 'Quad', value: '', subject: Variable { termType: 'Variable', value: 's' }, predicate: NamedNode { termType: 'NamedNode', value: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' }, object: NamedNode { termType: 'NamedNode', value: 'http://www.w3.org/ns/dcat#Dataset' }, graph: DefaultGraph { termType: 'DefaultGraph', value: '' }, type: 'pattern' }, metadata: { requestTime: 1244, pageSize: 100, cardinality: { type: 'exact', value: 100 }, first: 'https://opendata.picturae.com/catalog.ttl?page=1', next: 'https://opendata.picturae.com/catalog.ttl?page=2', previous: null, last: 'https://opendata.picturae.com/catalog.ttl?page=3', searchForms: { values: [] }, canContainUndefs: false, order: undefined, availableOrders: undefined, variables: [ Variable { termType: 'Variable', value: 's' } ] }, actor: 'urn:comunica:default:rdf-join/actors#inner-multi-bind' }
[[2023-03-20T20:20:06.169Z]  DEBUG: Determined physical join operator 'inner-nested-loop' { entries: 2, variables: [ [ 'i' ], [ 'issued' ] ], costs: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': 2501, 'inner-symmetric-hash': 2492, 'inner-nested-loop': 2489, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined }, coefficients: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': { iterations: 2, persistedItems: 1, blockingItems: 1, requestTime: 24.88 }, 'inner-symmetric-hash': { iterations: 2, persistedItems: 2, blockingItems: 0, requestTime: 24.88 }, 'inner-nested-loop': { iterations: 1, persistedItems: 0, blockingItems: 0, requestTime: 24.88 }, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined } }
[2023-03-20T20:20:06.173Z]  INFO: Requesting https://opendata.picturae.com/catalog.ttl?page=2 { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v18.14.1; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2023-03-20T20:20:07.148Z]  INFO: Identified as file source: https://opendata.picturae.com/catalog.ttl?page=2 { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }
[2023-03-20T20:20:07.163Z]  INFO: Requesting https://opendata.picturae.com/catalog.ttl?page=3 { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v18.14.1; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2023-03-20T20:20:07.583Z]  INFO: Identified as file source: https://opendata.picturae.com/catalog.ttl?page=3 { actor: 'urn:comunica:default:rdf-resolve-hypermedia/actors#none' }
[2023-03-20T20:20:07.588Z]  DEBUG: Determined physical join operator 'inner-nested-loop' { entries: 2, variables: [ [ 'i' ], [ 'issued' ] ], costs: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': 2501, 'inner-symmetric-hash': 2492, 'inner-nested-loop': 2489, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined }, coefficients: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': { iterations: 2, persistedItems: 1, blockingItems: 1, requestTime: 24.88 }, 'inner-symmetric-hash': { iterations: 2, persistedItems: 2, blockingItems: 0, requestTime: 24.88 }, 'inner-nested-loop': { iterations: 1, persistedItems: 0, blockingItems: 0, requestTime: 24.88 }, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined } }
[2023-03-20T20:20:07.595Z]  DEBUG: Determined physical join operator 'inner-nested-loop' { entries: 2, variables: [ [ 'i' ], [ 'issued' ] ], costs: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': 2501, 'inner-symmetric-hash': 2492, 'inner-nested-loop': 2489, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined }, coefficients: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': { iterations: 2, persistedItems: 1, blockingItems: 1, requestTime: 24.88 }, 'inner-symmetric-hash': { iterations: 2, persistedItems: 2, blockingItems: 0, requestTime: 24.88 }, 'inner-nested-loop': { iterations: 1, persistedItems: 0, blockingItems: 0, requestTime: 24.88 }, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined } }
[2023-03-20T20:20:07.600Z]  DEBUG: Determined physical join operator 'inner-nested-loop' { entries: 2, variables: [ [ 'i' ], [ 'issued' ] ], costs: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': 2501, 'inner-symmetric-hash': 2492, 'inner-nested-loop': 2489, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined }, coefficients: { 'inner-none': undefined, 'inner-single': undefined, 'inner-multi-empty': undefined, 'inner-bind': undefined, 'inner-hash': { iterations: 2, persistedItems: 1, blockingItems: 1, requestTime: 24.88 }, 'inner-symmetric-hash': { iterations: 2, persistedItems: 2, blockingItems: 0, requestTime: 24.88 }, 'inner-nested-loop': { iterations: 1, persistedItems: 0, blockingItems: 0, requestTime: 24.88 }, 'optional-bind': undefined, 'optional-nested-loop': undefined, 'minus-hash': undefined, 'minus-hash-undef': undefined, 'inner-multi-smallest': undefined } }

<snip>

{"c":"\"100\"^^http://www.w3.org/2001/XMLSchema#integer"}
```

Only **100** resources, so only the first page of them, are returned. All resources have the predicate `dct:issued`. We can validate this by replacing `dct:identifier` with `dct:issued`, which returns 209 results again.

____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.6.9
| node             | v18.14.1
| npm              | 9.3.1
| yarn             | 1.22.19
| Operating System | darwin (Darwin 22.3.0)

**Comment by ddeboer** [comment] 2023-03-21 10:52
@rubensworks Is this an easy fix on your side? If not, I will implement a workaround on ours.

**Comment by rubensworks** [comment] 2023-03-21 11:47
Not sure yet, will look into it next week.

**Comment by ddeboer** [comment] 2024-05-02 12:10
@rubensworks This issue was closed, but the situation persists where 

`comunica-sparql -l debug 'https://opendata.picturae.com/catalog.ttl?page=1' 'select (count(?s) as ?c) {?s a <http://www.w3.org/ns/dcat#Dataset> ; <http://purl.org/dc/terms/identifier> ?i; <http://purl.org/dc/terms/issued> ?issued }'
` 

returns only the first page (100 results), not all (209 results).

**Comment by rubensworks** [comment] 2024-05-02 12:23
Probably a regression in v3.

We should make sure to add a proper integration test for this case.

But at least we know where to fix the problem now.

**Comment by rubensworks** [comment] 2024-05-11 12:15
@ddeboer This has been fixed in release 3.1.1!

**Comment by ddeboer** [comment] 2024-06-18 11:54
@rubensworks Are you sure? I still don’t get subsequent Hydra pages in my app, nor from the CLI:

```shell
comunica-sparql 'https://archief.nl/id/datacatalog/toegang' 'select (count(?s) as ?count) {?s a <http://schema.org/Dataset>}'
[
{"count":"\"500\"^^http://www.w3.org/2001/XMLSchema#integer"}
]
```

That’s only the first page, with 500 `schema:Dataset`s. There are 15 pages in total.

```
comunica-sparql -v
| software         | version
| ---------------- | -------
| Comunica Engine  | 3.1.0
| node             | v20.14.0
| npm              | 10.7.0
| yarn             | _Yarn is unavailable_
| Operating System | darwin (Darwin 23.5.0)
```

Not sure why it says 3.1.0, because:

```
npm list -g | grep comunica
/opt/homebrew/lib
├── @comunica/query-sparql@3.1.2
```

**Comment by rubensworks** [comment] 2024-06-18 12:49
The previously reported query seems to work fine still, so this is probably another (but possible related) problem.

**Comment by rubensworks** [comment] 2024-06-26 08:27
Hi @ddeboer, I just had a quick look into your last problem, and from the looks of it, this appears to be a problem with the server.

There appears to be a redirect from `https://archief.nl/id/datacatalog/toegang` to `https://archief.nl/doc/datacatalog/toegang?page=1` (which is fine, and Comunica followes it).
However, the metadata is linked onto the `https://archief.nl/id/datacatalog/toegang?page=1` URL, while Comunica only looks for metadata on `https://archief.nl/doc/datacatalog/toegang?page=1` (due to the redirect).

If this worked before on your end, then I suspect something changed in this server, because Comunica always used to work like this.

**Comment by ddeboer** [comment] 2024-06-26 08:37
Hey @rubensworks, thanks for investigating! To be clear: this has never worked for us with Comunica, so we work around this by handling the Hydra pagination in our code. 

I see the redirection to `doc` but not to `?page=1`:

```sh
curl -v -H Accept:application/ld+json 'https://archief.nl/id/datacatalog/toegang'
...
<  location: /doc/datacatalog/toegang
```

Also:

```sh
comunica-sparql 'https://archief.nl/id/datacatalog/toegang' 'select * { ?s ?p ?o} limit 1' --logLevel debug
[2024-06-26T08:34:51.988Z]  INFO: Requesting https://archief.nl/id/datacatalog/toegang { headers: { accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18,application/json;q=0.135,text/shaclc;q=0.1,text/shaclc-ext;q=0.05', 'user-agent': 'Comunica/actor-http-fetch (Node.js v20.14.0; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2024-06-26T08:34:52.353Z]  INFO: Requesting https://schema.org/ { headers: { accept: 'application/ld+json', 'user-agent': 'Comunica/actor-http-fetch (Node.js v20.14.0; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2024-06-26T08:34:52.382Z]  INFO: Requesting https://schema.org/docs/jsonldcontext.jsonld { headers: { accept: 'application/ld+json', 'user-agent': 'Comunica/actor-http-fetch (Node.js v20.14.0; darwin)' }, method: 'GET', actor: 'urn:comunica:default:http/actors#fetch' }
[2024-06-26T08:35:00.624Z]  INFO: Identified as file source: https://archief.nl/doc/datacatalog/toegang { actor: 'urn:comunica:default:query-source-identify-hypermedia/actors#none' }
[
{"s":"https://archief.nl/id/datacatalog/toegang?page=1","p":"http://www.w3.org/ns/hydra/core#first","o":"https://archief.nl/id/datacatalog/toegang?page=1"}
]
```

**Comment by rubensworks** [comment] 2024-06-26 08:59
> I see the redirection to doc but not to ?page=1:

Ah indeed, you seem to be right.
But if metadata is attached to the `?page=1`-based URL, then it should also be redirected to the `?page=1`-based URL.

> Can the server fix this by replacing like this?

That should work, yes. (if the comment above is also taken into account)
An alternative solution is to make these URLs relative to the base URL, which may be easier and more future-proof in case the URL would change in the future.

**Comment by rubensworks** [comment] 2024-06-26 17:52
Closing this in the meantime. Happy to re-open if needed.

**Closed by rubensworks** 2024-06-26 17:52 UTC
Labels: bug 🐛, difficulty:high, effort:medium
