### ISSUE TITLE
syntactic sugar for RDF lists not supported with `type: "stringSource"`

### ISSUE THREAD

**Issue by smessie** [comunica/comunica#1161] opened 2023-02-20 13:20 UTC
#### Issue type:

- :bug: Bug 

____
#### Description:

When passing the content as string and not as URL, the syntactic sugar for RDF lists does not work.

For completeness:

Code:

```js
    async parseSchema(n3schema) {
      const query = `
      PREFIX ui: <http://www.w3.org/ns/ui#>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      SELECT ?field WHERE {
        <${this.schema}> ui:parts ?list .
        ?list rdf:rest*/rdf:first ?field .
      }
      `;

      const fields = await (
        await this.engine.queryBindings(query, {
          sources: [
            {
              type: "stringSource",
              value: n3schema,
              mediaType: "text/n3",
              baseIRI: this.schema.split("#")[0],
            },
          ],
        })
      ).toArray();

      console.log("fields", fields);

      return fields.map((row) => {
        return {
          field: row.get("field").value,
        };
      });
    },
```

`n3Schema` that does **not** work because the `?s ?p ( ?i1 ?i1 ).` syntax is used:

(same as content of https://solid.smessie.com/private/tests/forms/solid-ui-books.ttl)

```
@prefix ex: <https://example.org/#> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix ui: <http://www.w3.org/ns/ui#>.
@prefix solid: <http://www.w3.org/ns/solid/terms#>.
@prefix skos: <http://www.w3.org/2004/02/skos/core#>.
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix : <#> .

:this
    a ui:Form ;
    ui:parts (
        :titleField
        :authorField
        :ratingField
        :reviewField
    ).

:titleField 
    a ui:SingleLineTextField ;
    ui:property dc:title ;
    ui:label "Title".

:authorField 
    a ui:SingleLineTextField ;
    ui:property dc:creator ;
    ui:label "Author".

:ratingField
    a ui:Choice ;
    ui:property ex:rating ;
    ui:label "Rate this book" ;
    ui:from :ChoiceValue .

:ChoiceValue 
    a owl:Class.

ex:NotLikeIt 
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★ - I don't like it" .

ex:ItWasOk
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★ - It was ok" .

ex:LikedIt
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★★ - I liked it" .

ex:ReallyLikedIt
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★★★ - I really liked it" .

ex:Amazing
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★★★★ - It was amazing" .

:reviewField
    a ui:MultiLineTextField ;
    ui:property dc:description ;
    ui:label "Review".
```

`n3Schema` that does work because I rewrote the syntactic sugar to triples with `rdf:first` and `rdf:rest`:

(same as content of https://solid.smessie.com/private/tests/forms/solid-ui-books-full.ttl)

```

@prefix ex: <https://example.org/#> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix ui: <http://www.w3.org/ns/ui#>.
@prefix solid: <http://www.w3.org/ns/solid/terms#>.
@prefix skos: <http://www.w3.org/2004/02/skos/core#>.
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix : <#> .

:this
    a ui:Form ;
    ui:parts :i1.

:i1 rdf:first :titleField; rdf:rest :i2.
:i2 rdf:first :authorField; rdf:rest :i3.
:i3 rdf:first :ratingField; rdf:rest :i4.
:i4 rdf:first :reviewField; rdf:rest rdf:nil.

:titleField 
    a ui:SingleLineTextField ;
    ui:property dc:title ;
    ui:label "Title".

:authorField 
    a ui:SingleLineTextField ;
    ui:property dc:creator ;
    ui:label "Author".

:ratingField
    a ui:Choice ;
    ui:property ex:rating ;
    ui:label "Rate this book" ;
    ui:from :ChoiceValue .

:ChoiceValue 
    a owl:Class.

ex:NotLikeIt 
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★ - I don't like it" .

ex:ItWasOk
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★ - It was ok" .

ex:LikedIt
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★★ - I liked it" .

ex:ReallyLikedIt
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★★★ - I really liked it" .

ex:Amazing
    a skos:Concept , :ChoiceValue ;
    skos:prefLabel "★★★★★ - It was amazing" .

:reviewField
    a ui:MultiLineTextField ;
    ui:property dc:description ;
    ui:label "Review".
```

Mind though, it works for comunica in general, working example where it is executed via live version, because it is loaded from the URI: https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsolid.smessie.com%2Fprivate%2Ftests%2Fforms%2Fsolid-ui-books.ttl&query=PREFIX%20ui%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fui%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20%3A%20%3Chttps%3A%2F%2Fsolid.smessie.com%2Fprivate%2Ftests%2Fforms%2Fsolid-ui-books.ttl%23%3E%0A%0ASELECT%20%3Ffield%20WHERE%20%7B%0A%20%20%3Athis%20ui%3Aparts%20%3Flist%20.%0A%20%20%3Flist%20rdf%3Arest*%2Frdf%3Afirst%20%3Ffield%20.%0A%7D 

____
#### Environment:

```
➜ comunica-sparql -v
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.6.7 
| node             | v16.17.1
| npm              | 8.15.0
| yarn             | 1.22.19
| Operating System | darwin (Darwin 22.3.0)
```

in dependencies: `"@comunica/query-sparql-solid": "^2.4.0",`

**Comment by rubensworks** [comment] 2023-02-20 13:25
Probably a similar issue as the bnode issue fixed in https://github.com/comunica/comunica/commit/4a0992d5f757c356c2ba6662b8b512c712bdc0c8

> n3Schema that does work because I rewrote the syntactic sugar to triples with rdf:first and rdf:rest:

Are you using blank nodes in that case?

@surilindur @constraintAutomaton Perhaps you two may have some insights into this issue?

**Comment by smessie** [comment] 2023-02-20 13:27
> Are you using blank nodes in that case?

With the syntactic sugar, it is written as 
```
:this
    a ui:Form ;
    ui:parts (
        :titleField
        :authorField
        :ratingField
        :reviewField
    ).
```
So yes, this uses blank nodes under the hood.

**Comment by smessie** [comment] 2023-03-11 17:00
Any update on this @rubensworks ?
I'm encountering the same issue in another place for my thesis so I'm stuck again :/

Now it's for blank nodes in general and not only lists

[Example here](https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsolid.smessie.com%2Fprivate%2Ftests%2Ftodos%2Fcomunica-test.ttl&query=PREFIX%20ex%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0APREFIX%20pol%3A%20%3Chttps%3A%2F%2Fwww.example.org%2Fns%2Fpolicy%23%3E%0APREFIX%20fno%3A%20%3Chttps%3A%2F%2Fw3id.org%2Ffunction%2Fontology%23%3E%0A%0ASELECT%20%3Fid%20%3Fpolicy%20%3FexecutionTarget%20%3FinsertTriples%20%3FdeleteTriples%20%3Fip%20%3Fio%20%3Fdp%20%3Fdo%20WHERE%20%7B%0A%20%20%3Fid%20pol%3Apolicy%20%3Fpolicy%20.%0A%20%20%3Fpolicy%20a%20fno%3AExecution%20.%0A%20%20%3Fpolicy%20fno%3Aexecutes%20%3FexecutionTarget%20.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fpolicy%20ex%3AinsertTriples%20%3FinsertTriples%20.%0A%20%20%20%20%3FinsertTriples%20%3Fip%20%3Fio%20.%0A%20%20%7D%20.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fpolicy%20ex%3AdeleteTriples%20%3FdeleteTriples%20.%0A%20%20%20%20%3FdeleteTriples%20%3Fdp%20%3Fdo%20.%0A%20%20%7D%20.%0A%7D) which is working in the live version but not with `type: "stringSource"`.

Data:
```turtle
@prefix ex: <http://example.org/>.
@prefix ncal: <https://www.semanticdesktop.org/ontologies/2007/04/02/ncal/>.
@prefix pol: <https://www.example.org/ns/policy#>.
@prefix fno: <https://w3id.org/function/ontology#>.

ex:CompletedPolicy pol:policy [
   a fno:Execution ;
   fno:executes ex:toggleCompleted ;
   ex:insertTriples [
       ncal:completed "2023-03-11T16:34:38.015Z";
       ncal:todoStatus ncal:completedStatus
   ] ;
   ex:deleteTriples [
      ncal:todoStatus ncal:inProcessStatus
   ]
] .
```

Query:
```turtle
PREFIX ex: <http://example.org/>
PREFIX pol: <https://www.example.org/ns/policy#>
PREFIX fno: <https://w3id.org/function/ontology#>

SELECT ?id ?policy ?executionTarget ?insertTriples ?deleteTriples ?ip ?io ?dp ?do WHERE {
  ?id pol:policy ?policy .
  ?policy a fno:Execution .
  ?policy fno:executes ?executionTarget .
  OPTIONAL {
    ?policy ex:insertTriples ?insertTriples .
    ?insertTriples ?ip ?io .
  } .
  OPTIONAL {
    ?policy ex:deleteTriples ?deleteTriples .
    ?deleteTriples ?dp ?do .
  } .
}
```

**Comment by rubensworks** [comment] 2023-03-13 06:19
Pining @surilindur and @constraintAutomaton again.

**Comment by surilindur** [comment] 2023-03-15 14:32
Sorry about the delay, I was busy with other things. It seems the issue could be a mismatch between the prefix in the SPARQL query and the base IRI that gets passed for the data source parsing.

I used the data that was [linked earlier](https://solid.smessie.com/private/tests/forms/solid-ui-books.ttl), with the same prefix as in the live version linked above. So the query looked like this:
```
PREFIX ui: <http://www.w3.org/ns/ui#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <https://solid.smessie.com/private/tests/forms/solid-ui-books.ttl#>

SELECT ?field WHERE {
    :this ui:parts ?list .
    ?list rdf:rest*/rdf:first ?field .
}
```
And the source definition in the JavaScript code (following your example earlier) looked like this:
```
const source = {
  type: 'stringSource',
  value: sourceString,
  mediaType: 'text/turtle',
  baseIRI: 'https://solid.smessie.com/private/tests/forms/solid-ui-books.ttl', // <- this is where it failed, I guess
}
```
And it worked with the latest Comunica (`v2.6.9` at the time of writing). Maybe the base IRI that gets assigned to the source does not match what the SPARQL query contains in your application? If the IRIs in the data (after parsing, taking into account the base IRI) are different from the ones in the SPARQL query it will not find the data (obviously). I guess that is the problem.

Hopefully that helps. At least it does not seem like a bug in the string source actor, thankfully. :sweat_smile:

**Comment by smessie** [comment] 2023-03-16 09:25
Thanks for looking into this @surilindur and sorry if this was due to a problem from my side!

Did you confirm getting this to work with changing the `baseIRI`? I am trying this but did not manage to get this working yet, but I'll keep trying in the meantime.

For completeness, my stringSource:
```
@base <https://solid.smessie.com/private/tests/todos/ncal-todos.ttl#> .
@prefix cal: <http://www.w3.org/2002/12/cal/ical#>.
@prefix ex: <http://example.org/>.
@prefix schema: <http://schema.org/>.
@prefix ncal: <https://www.semanticdesktop.org/ontologies/2007/04/02/ncal/>.
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix pol: <https://www.example.org/ns/policy#>.
@prefix fno: <https://w3id.org/function/ontology#>.

ex:CompletedPolicy pol:policy _:sk_0.
_:sk_0 a fno:Execution.
_:sk_0 fno:executes ex:updateResource.
_:sk_0 ex:insertTriples _:sk_1.
_:sk_1 ncal:completed "2023-03-16T09:14:09.110Z".
_:sk_1 ncal:todoStatus ncal:completedStatus.
_:sk_0 ex:deleteTriples _:sk_2.
_:sk_2 ncal:todoStatus ncal:inProcessStatus.
_:sk_0 ex:subject <https://solid.smessie.com/private/tests/todos/ncal-todos.ttl##t1>.
```

My query:
```
PREFIX ex: <http://example.org/>
PREFIX pol: <https://www.example.org/ns/policy#>
PREFIX fno: <https://w3id.org/function/ontology#>

SELECT ?s ?p ?o WHERE {
  ?id pol:policy [
    a fno:Execution ;
    fno:executes ex:updateResource ;
    ex:subject ?s ;
    ex:insertTriples [
      ?p ?o
    ]
  ] .
}
```

My baseIRI: `https://solid.smessie.com/private/tests/todos/ncal-todos.ttl#`

**Comment by surilindur** [comment] 2023-03-16 12:48
When I execute the query on the data as it is in your previous message, I get the following bindings out:
```
{
  "p": "https://www.semanticdesktop.org/ontologies/2007/04/02/ncal/completed",
  "o": "2023-03-16T09:14:09.110Z",
  "s": "https://solid.smessie.com/private/tests/todos/ncal-todos.ttl##t1"
}
{
  "p": "https://www.semanticdesktop.org/ontologies/2007/04/02/ncal/todoStatus",
  "o": "https://www.semanticdesktop.org/ontologies/2007/04/02/ncal/completedStatus",
  "s": "https://solid.smessie.com/private/tests/todos/ncal-todos.ttl##t1"The `@base` in the data 
}
```
Maybe there is something else happening with the way the query and the data are set up that breaks it for your setup?

**Comment by rubensworks** [comment] 2023-03-16 14:09
> so I guess @comunica/query-sparql-solid will need an update so the patched @comunica/actor-rdf-resolve-quad-pattern-string-source gets included 

Just resetting your lockfile and node_modules, and re-installing should give you the latest version of `@comunica/query-sparql`.

**Comment by smessie** [comment] 2023-03-16 14:41
> Just resetting your lockfile and node_modules, and re-installing should give you the latest version of `@comunica/query-sparql`.

Removing both package-lock.json and node_modules and rerunning `npm i` actually do not seem to fix it while using `@comunica/query-sparql-solid`. Is this only for me?

**Comment by rubensworks** [comment] 2023-03-28 13:45
Can you try with yarn? It's possible npm doesn't pull in the latest possible version in the semver range.

In any case, we should update the comunica version in https://github.com/comunica/comunica-feature-solid (PR is welcome).

Closing this issue in any case.

**Closed by rubensworks** 2023-03-28 13:45 UTC
Labels: bug 🐛

**Comment by rubensworks** [comment] 2023-12-22 06:38
> However, manually putting that reasonerResult online in a resource and using its URL results in a defined and expected ?contentType.

Is this a N3 or Turtle resource in this case? Or do both work correctly?

**Comment by smessie** [comment] 2023-12-22 08:17
It was Turtle (.ttl), however when I save the resource as N3 (.n3), it also works via the web version ([Turtle live](https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsolid.smessie.com%2Fthesis%2Fforms%2Fcomunica-list-test.ttl&query=%20%20%20%20%20%20PREFIX%20ex%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0A%20%20%20%20%20%20PREFIX%20pol%3A%20%3Chttps%3A%2F%2Fw3id.org%2FDFDP%2Fpolicy%23%3E%0A%20%20%20%20%20%20PREFIX%20fno%3A%20%3Chttps%3A%2F%2Fw3id.org%2Ffunction%2Fontology%23%3E%0A%20%20%20%20%20%20PREFIX%20http%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2011%2Fhttp%23%3E%0A%0A%20%20%20%20%20%20SELECT%20%3FexecutionTarget%20%3Fmethod%20%3Furl%20%3FcontentType%20WHERE%20%7B%0A%20%20%20%20%20%20%20%20%3Fid%20pol%3Apolicy%20%3Fpolicy%20.%0A%20%20%20%20%20%20%20%20%3Fpolicy%20a%20fno%3AExecution%20.%0A%20%20%20%20%20%20%20%20%3Fpolicy%20fno%3Aexecutes%20%3FexecutionTarget%20.%0A%20%20%20%20%20%20%20%20%3Fpolicy%20http%3ArequestURI%20%3Furl%20.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fpolicy%20http%3AmethodName%20%3Fmethod%20%7D%20.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fpolicy%20http%3Aheaders%20(%20%5B%20http%3AfieldName%20%22Content-Type%22%20%3B%20http%3AfieldValue%20%3FcontentType%20%5D%20)%20%7D%20.%0A%20%20%20%20%20%20%7D) - [N3 live](https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsolid.smessie.com%2Fthesis%2Fforms%2Fcomunica-test-list-n3.n3&query=%20%20%20%20%20%20PREFIX%20ex%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0A%20%20%20%20%20%20PREFIX%20pol%3A%20%3Chttps%3A%2F%2Fw3id.org%2FDFDP%2Fpolicy%23%3E%0A%20%20%20%20%20%20PREFIX%20fno%3A%20%3Chttps%3A%2F%2Fw3id.org%2Ffunction%2Fontology%23%3E%0A%20%20%20%20%20%20PREFIX%20http%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2011%2Fhttp%23%3E%0A%0A%20%20%20%20%20%20SELECT%20%3FexecutionTarget%20%3Fmethod%20%3Furl%20%3FcontentType%20WHERE%20%7B%0A%20%20%20%20%20%20%20%20%3Fid%20pol%3Apolicy%20%3Fpolicy%20.%0A%20%20%20%20%20%20%20%20%3Fpolicy%20a%20fno%3AExecution%20.%0A%20%20%20%20%20%20%20%20%3Fpolicy%20fno%3Aexecutes%20%3FexecutionTarget%20.%0A%20%20%20%20%20%20%20%20%3Fpolicy%20http%3ArequestURI%20%3Furl%20.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fpolicy%20http%3AmethodName%20%3Fmethod%20%7D%20.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%20%3Fpolicy%20http%3Aheaders%20(%20%5B%20http%3AfieldName%20%22Content-Type%22%20%3B%20http%3AfieldValue%20%3FcontentType%20%5D%20)%20%7D%20.%0A%20%20%20%20%20%20%7D)).
Note, however, that when I check the response Content-Type in the browser network tab, it is stated as `application/n-quads` instead of `text/n3`.
This is the same for in the app: with the uri as source (.n3 resource) it works, but checking the network tab, it has response Content-Type of `application/n-quads` instead of `text/n3`.
I went ahead and further investigated this in my app: when I use string source with `mediaType: "application/n-quads"` it also works (just as with `text/turtle`), only with `text/n3` it does not work.

**Comment by surilindur** [comment] 2024-01-11 14:39
The code that performs parsing of `text/n3` (among others) [seems to just pass the input](https://github.com/comunica/comunica/blob/1fe8472ccb1f1f5365127be47b0c937be82960a5/packages/actor-rdf-parse-n3/lib/ActorRdfParseN3.ts#L38) to a `StreamParser` from N3.js. Since `text/turtle` and `application/n-quads` work, maybe the issue could be related to N3.js library and how it parses `text/n3`?

Since the issue is related to blank nodes in lists, could it be the same as rdfjs/N3.js#332?

That is just a thought, but I wanted to note it down before I forget.

**Comment by constraintAutomaton** [comment] 2024-01-22 10:28
I'm going to look into it soon.

**Comment by surilindur** [comment] 2024-01-22 12:09
Based on the example input by @smessie in an earlier comment, here is a short code snippet to reproduce the issue when using the `n3` library to parse `text/n3` with blank nodes in it, which is an issue in the N3 library itself and not Comunica:
```javascript
const N3 = require('n3')

const reasonerResult = `
@prefix ex: <http://example.org/>.
@prefix pol: <https://w3id.org/DFDP/policy#>.
@prefix fno: <https://w3id.org/function/ontology#>.
@prefix http: <http://www.w3.org/2011/http#>.

ex:HttpPolicy pol:policy _:sk_0.
_:sk_0 a fno:Execution.
_:sk_0 fno:executes http:Request.
_:sk_0 http:requestURI <https://httpbin.org/post>.
_:sk_0 http:methodName "POST".
_:sk_0 http:headers (_:sk_1).
_:sk_1 http:fieldName "Content-Type".
_:sk_1 http:fieldValue "application/ld+json".
`

const parser = new N3.Parser({ format: 'text/n3' }) // changing this format fixes it
const writer = new N3.Writer({ format: 'application/n-quads' })
const output = writer.quadsToString(parser.parse(reasonerResult))

console.log(output)
```
This will output the following:
```
<http://example.org/HttpPolicy> <https://w3id.org/DFDP/policy#policy> _:b0_sk_0 .
_:b0_sk_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/function/ontology#Execution> .
_:b0_sk_0 <https://w3id.org/function/ontology#executes> <http://www.w3.org/2011/http#Request> .
_:b0_sk_0 <http://www.w3.org/2011/http#requestURI> <https://httpbin.org/post> .
_:b0_sk_0 <http://www.w3.org/2011/http#methodName> "POST" .
_:n3-0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:.sk_1 .
_:n3-0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b0_sk_0 <http://www.w3.org/2011/http#headers> _:n3-0 .
_:b0_sk_1 <http://www.w3.org/2011/http#fieldName> "Content-Type" .
_:b0_sk_1 <http://www.w3.org/2011/http#fieldValue> "application/ld+json" .
```
One can see how the `#first` entry of the list is declared as `_:.sk_1` which is not correct and has an extra `.` added to it. This is probably what breaks the query, too, because the query cannot find the blank node that is supposed to be first in that list.
